Repository build-on-aws/content, pull requests merged in 2023-10, with the labels that each got.

#769 [New Tutorial] Building an Amazon EKS Cluster Preconfigured to Run Asynchronous Batch
  tutorials/navigating-amazon-eks/eks-cluster-batch-processing/index.md
Labels: changes requested, editorial review in progress, tutorial, technical review complete, 8112

#731 [New Tutorial] EKS tutorial Monitor Container Applications
  tutorials/eks-monitor-containerized-applications/images/Container_Insight_Query.png
  tutorials/eks-monitor-containerized-applications/images/Container_Insights.png
  tutorials/eks-monitor-containerized-applications/images/resource_monitoring.png
  tutorials/eks-monitor-containerized-applications/index.md
Labels: final review, editorial review in progress, tutorial, technical review complete

#813 [New post] Simonhanmer issue 764
  posts/now-you-see-me-now-you-dont/01-the-case-of-the-disappearing-s3-keys/images/architecture.png
  posts/now-you-see-me-now-you-dont/01-the-case-of-the-disappearing-s3-keys/images/s3-rollout.png
  posts/now-you-see-me-now-you-dont/01-the-case-of-the-disappearing-s3-keys/index.md
  posts/now-you-see-me-now-you-dont/02-Handling-batch-errors-with-the-lambda-sqs-poller/images/architecture.png
  posts/now-you-see-me-now-you-dont/02-Handling-batch-errors-with-the-lambda-sqs-poller/images/sqs_batch.png
  posts/now-you-see-me-now-you-dont/02-Handling-batch-errors-with-the-lambda-sqs-poller/index.md
  posts/now-you-see-me-now-you-dont/series.md
Labels: blog, community contribution, ready for one-step review

#812 Initial 2 page commit
  posts/codewhisperer-for-lecturers/images/AdobeStock_520205725_AdobeStock_167836824.webp
  posts/codewhisperer-for-lecturers/images/AdobeStock_607140721s.webp
  posts/codewhisperer-for-lecturers/index.md
Labels: blog, Draft

#754 [New Tutorial] Automatically Manage DNS Records for Your Microservices in Amazon EKS with ExternalDNS
  tutorials/automating-dns-records-for-microservices-using-externaldns/images/arch.png
  tutorials/automating-dns-records-for-microservices-using-externaldns/images/out.png
  tutorials/automating-dns-records-for-microservices-using-externaldns/index.md
Labels: final review, tutorial, technical review complete, editorial review complete, 8112

#737 New post:" Unlock the power of Unstructured Data: From Embeddings to In Context Learning – Build a Full stack Q&A Chatbot with Langchain, and LLM Models on Sagemaker
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/cloudformation-qa-api-output.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/deployed-endpoints.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/dns-name-website.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/document-processing-pipeline.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/ecr-qa-container.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/embedding1.jpg
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/embedding2.jpg
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/embeddings-save-vectordb.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/opensearch-embeddings-1.jpg
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/opensearch-embeddings-3.jpg
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/overallarchitecture.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/realtime-in-context-learning-workflow.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/save-embeddings-vectordb-ecr.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/t5-flan-xxl-2.jpg
  tutorials/fullstack-llm-langchain-chatbot-on-aws/images/website-1.png
  tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
Labels: tutorial, technical review complete, editorial review complete, 8112

#824 [New post] 3 Must-Know Tips for AWS re:Invent
  posts/three-tips-for-reinvent/images/aws-reinvent-sign.jpg
  posts/three-tips-for-reinvent/images/dev-lounge.jpg
  posts/three-tips-for-reinvent/images/grand-canyon.jpeg
  posts/three-tips-for-reinvent/images/linkedin-image-1.PNG
  posts/three-tips-for-reinvent/images/linkedin-image-2.PNG
  posts/three-tips-for-reinvent/images/linkedin-image-3.PNG
  posts/three-tips-for-reinvent/images/re-invent-hotel-map.jpg
  posts/three-tips-for-reinvent/images/reinvent-badging-area.jpg
  posts/three-tips-for-reinvent/images/vegas-show.jpg
  posts/three-tips-for-reinvent/index.md
Labels: blog, ready for one-step review

#825 Can generative ai be used to learn about cybersecurity
  posts/can-generative-ai-be-used-to-learn-about-cybersecurity/images/2023-10-04_16-16-17.jpg
  posts/can-generative-ai-be-used-to-learn-about-cybersecurity/images/2023-10-04_16-17-56.webp
  posts/can-generative-ai-be-used-to-learn-about-cybersecurity/images/2023-10-04_16-20-05.jpg
  posts/can-generative-ai-be-used-to-learn-about-cybersecurity/images/2023-10-04_16-21-08.jpg
  posts/can-generative-ai-be-used-to-learn-about-cybersecurity/images/An image depicting someone learning about cybersecurity._.png
  posts/can-generative-ai-be-used-to-learn-about-cybersecurity/index.md
Labels: blog, ready for one-step review

#826 A Network Engineers Guide to Generative AI
  posts/a-network-engineers-guide-to-generative-ai/images/attention-model.png
  posts/a-network-engineers-guide-to-generative-ai/images/bedrock.gif
  posts/a-network-engineers-guide-to-generative-ai/images/chain-of-verification.png
  posts/a-network-engineers-guide-to-generative-ai/images/code-sample.png
  posts/a-network-engineers-guide-to-generative-ai/index.md
Labels: blog, ready for one-step review

#829 New Post: Get Ready to Level Up Your AWS Skills at re:Invent 2023 GameDays
  posts/reinvent2023-gamedays/images/f1.jpg
  posts/reinvent2023-gamedays/images/gameday_vibe.jpg
  posts/reinvent2023-gamedays/images/riot_swag.jpg
  posts/reinvent2023-gamedays/images/scoreboard.jpg
  posts/reinvent2023-gamedays/index.md
Labels: blog, ready for one-step review

#687 New Tutorial: Securely Access Resources with IAM Service Roles
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/clean-up-1.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/clean-up-2.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-1.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-10.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-2.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-3.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-4.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-5.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-6.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-7.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-8.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/cloudformation-9.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/ec2-1.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/ec2-2.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/ec2-3.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/ec2-4.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/ec2-5.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/ec2-6.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-1.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-2.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-3.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-4.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-5.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-6.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-7.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/iam-8.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/identity.jpg
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/role-1.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/role-2.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/role-3.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/role-4.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/role-5.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/images/role-6.png
  tutorials/practical-cloud-guide/securely-access-resources-with-iam-service-roles/index.md
  tutorials/practical-cloud-guide/series.md
Labels: final review, tutorial, technical review complete, editorial review complete, 8112

#831 using-generative-ai-for-cybersecurity-work
  posts/using-generative-ai-for-cybersecurity-work/images/2023-10-06_12-48-39.jpg
  posts/using-generative-ai-for-cybersecurity-work/images/cwdemo.gif
  posts/using-generative-ai-for-cybersecurity-work/index.md
Labels: blog, ready for one-step review

#835 [New Post] Friday fun llm
  posts/friday-fun-style-changing-reinvent-guide/images/bedrock_chat.png
  posts/friday-fun-style-changing-reinvent-guide/images/pirate.jpeg
  posts/friday-fun-style-changing-reinvent-guide/images/shakespeare.jpeg
  posts/friday-fun-style-changing-reinvent-guide/index.md
Labels: blog, ready for one-step review

#843 updating blog link - 3 Must-Know Tips for AWS re:Invent
  posts/three-tips-for-reinvent/index.md
Labels: blog, ready for one-step review

#842 [New post] resilience-at-reinvent
  posts/resilience-at-reinvent/images/figure1.webp
  posts/resilience-at-reinvent/images/figure2.webp
  posts/resilience-at-reinvent/images/figure3.webp
  posts/resilience-at-reinvent/images/figure4.webp
  posts/resilience-at-reinvent/index.md
Labels: published, blog, ready for one-step review

#845 Valorant event post
  posts/learning-with-aws-heroes-and-riot-games/images/heroes.webp
  posts/learning-with-aws-heroes-and-riot-games/images/tournament.webp
  posts/learning-with-aws-heroes-and-riot-games/index.md
Labels: published, blog, ready for one-step review

#772 [New Post] Identifying proxy metrics for sustainability optimization
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image1.png
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image2.jpg
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image3.png
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image4.png
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image5.png
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image6.png
  posts/identifying-proxy-metrics-for-sustainability-optimization/images/image7.png
  posts/identifying-proxy-metrics-for-sustainability-optimization/index.md
Labels: blog, ready for one-step review

#851 Decoding AWS re:Invent | A guide for first-timers
  posts/decoding-aws-reinvent-a-guide-for-first-timers/index.md
Labels: blog, ready for one-step review

#854 Adding new post: Five Ways to Accelerate Product Development for Deve…
  posts/five-ways-to-accelerate-product-development-for-developers/images/aws-amazon-solutions.webp
  posts/five-ways-to-accelerate-product-development-for-developers/images/prototype.webp
  posts/five-ways-to-accelerate-product-development-for-developers/index.md
Labels: blog, ready for one-step review

#828 [New post] Generative AI apps with Amazon Bedrock - A getting started guide for Go developers
  concepts/amazon-bedrock-golang-getting-started/images/chat.png
  concepts/amazon-bedrock-golang-getting-started/images/streaming-chat.gif
  concepts/amazon-bedrock-golang-getting-started/index.md
Labels: author revisions requested, technical review complete, editorial review complete, quick guide, author revisions complete

#747 [Concepts] How-to-design-and-implement-an-effective-incident-response-strategy
  concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
Labels: final review in progress, fundamentals, technical review complete, editorial review complete

#684 New post: Building an observability strategy for resilience
  concepts/building-an-observability-strategy-for-resilience/images/aws-health.png
  concepts/building-an-observability-strategy-for-resilience/images/calculate-availability2.png
  concepts/building-an-observability-strategy-for-resilience/images/cloudwatch-synthetic-canary.png
  concepts/building-an-observability-strategy-for-resilience/images/continuous-improvement.png
  concepts/building-an-observability-strategy-for-resilience/images/image.txt
  concepts/building-an-observability-strategy-for-resilience/images/monitoring-heirarchy-v3.png
  concepts/building-an-observability-strategy-for-resilience/images/operational-health-dashboard.png
  concepts/building-an-observability-strategy-for-resilience/images/rto-rpo.png
  concepts/building-an-observability-strategy-for-resilience/index.md
Labels: published, technical review complete, editorial review complete, 8112

#859 [New Post] 5 things i wish i knew when i was new to aws
  posts/5-tips-i-wish-i-had-when-new-to-aws/images/tomatoes.webp
  posts/5-tips-i-wish-i-had-when-new-to-aws/index.md
Labels: blog, ready for one-step review

#863 Deploying Falcon-40B Open-Source LLM on Amazon SageMaker: A Comparative Guide
  posts/llm-falcon-40b-model-deployment-v2/images/falcon-training-parameters.png
  posts/llm-falcon-40b-model-deployment-v2/images/output-1.png
  posts/llm-falcon-40b-model-deployment-v2/images/refinedWeb-dataset.png
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-1.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-2.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-3.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-4.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-5.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-6.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-7.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-8.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/sagemaker-studio-jumpstart-9.jpeg
  posts/llm-falcon-40b-model-deployment-v2/images/tgi-1.png
  posts/llm-falcon-40b-model-deployment-v2/index.md
Labels: blog, ready for one-step review

#868 [Post] Deploy NGINX with AWS Cloudshell and Lightsail In Five Steps
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/cloudshell-1.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/cloudshell-2.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/cloudshell-3.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/cloudshell-4.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/cloudshell-5.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/lightsail-1.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/images/lightsail-2.png
  posts/deploy-nginx-with-aws-cloudshell-and-lightsail/index.md
Labels: blog, ready for one-step review

#869 [Post] Load Testing Wordpress Lightsail Instances
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-1.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-2.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-3.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-4.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-5.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-6.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-7.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-metrics-1.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-metrics-2.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-metrics-3.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-metrics-4.png
  posts/load-testing-wordpress-lightsail-instance/images/lightsail-metrics-5.png
  posts/load-testing-wordpress-lightsail-instance/images/locust-1.png
  posts/load-testing-wordpress-lightsail-instance/images/locust-2.png
  posts/load-testing-wordpress-lightsail-instance/images/locust-3.png
  posts/load-testing-wordpress-lightsail-instance/images/locust-4.png
  posts/load-testing-wordpress-lightsail-instance/images/number_of_users_1696836559.png
  posts/load-testing-wordpress-lightsail-instance/images/response_times_(ms)_1696836559.png
  posts/load-testing-wordpress-lightsail-instance/images/results-1.png
  posts/load-testing-wordpress-lightsail-instance/images/total_requests_per_second_1696836559.png
  posts/load-testing-wordpress-lightsail-instance/images/wp-1.png
  posts/load-testing-wordpress-lightsail-instance/images/wp-2.png
  posts/load-testing-wordpress-lightsail-instance/images/wp-3.webp
  posts/load-testing-wordpress-lightsail-instance/images/wp-4.png
  posts/load-testing-wordpress-lightsail-instance/index.md
Labels: blog, ready for one-step review

#872 [Post] Microservices with AWS Cloud9 and Lightsail
  posts/microservices-with-aws-cloud9-and-lightsail/images/cloud9-1.png
  posts/microservices-with-aws-cloud9-and-lightsail/images/cloud9-2.png
  posts/microservices-with-aws-cloud9-and-lightsail/images/cloud9-3.png
  posts/microservices-with-aws-cloud9-and-lightsail/images/cloud9-4.png
  posts/microservices-with-aws-cloud9-and-lightsail/images/cloud9-5.png
  posts/microservices-with-aws-cloud9-and-lightsail/images/cloud9-6.png
  posts/microservices-with-aws-cloud9-and-lightsail/index.md
Labels: blog, ready for one-step review

#873 Running the top open source Vector Database on AWS: What They Don't Tell You in the Quickstart Guide
  posts/running-the-top-open-source-vector-database-on-aws/index.md
Labels: blog, ready for one-step review, Draft

#841 New Tutorial: Easily Consume AWS Secrets Manager Secrets from your Amazon EKS Workloads
  tutorials/navigating-amazon-eks/eks-integrate-secrets-manager/index.md
  tutorials/navigating-amazon-eks/series.md
Labels: tutorial, technical review complete, editorial review complete, ready for final review

#883 [New blog] Improved developer experience of GraphQL APIs with JavaScript resolvers for AWS AppSync APIs
  posts/improved-developer-experience-of-graphql-apis-with-javascript-resolvers-for-aws-appsync-apis/images/AppSync-resolvers.webp
  posts/improved-developer-experience-of-graphql-apis-with-javascript-resolvers-for-aws-appsync-apis/images/PipelineResolverScreenshot.webp
  posts/improved-developer-experience-of-graphql-apis-with-javascript-resolvers-for-aws-appsync-apis/index.md
Labels: blog, community contribution, ready for one-step review

#884 [New Blog] Extend your saas offerings beyond aws boundaries using AWS PrivateLink and VPN
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/client-vpn-conceptual.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/end-customer-on-3rd-party-cloud-S2S-usecase.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/end-customer-on-aws-usecase.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/end-customer-on-premises-S2S-usecase.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/end-customer-on-premises-VPC-usecase.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/privatelink-conceptual.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/use-cases-to-solve-for.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/vpn-transit-gateway-conceptual.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/images/vpn-virtual-private-gateway-conceptual.png
  posts/extend-your-saas-offerings-beyond-AWS-boundaries-using-aws-privatelink-and-vpn/index.md
Labels: blog, ready for one-step review

#889 [Livestreams] Build On Answered shownotes
  livestreams/build-on-answered/2023-10-11/images/stream.webp
  livestreams/build-on-answered/2023-10-11/index.md
  livestreams/build-on-answered/2023-10-18/images/stream.webp
  livestreams/build-on-answered/2023-10-18/index.md
  livestreams/build-on-answered/2023-10-25/images/stream.webp
  livestreams/build-on-answered/2023-10-25/index.md
  livestreams/build-on-answered/index.md
Labels: livestream
