Repository build-on-aws/content, pull requests merged in 2023-07, with the labels that each got.

#441 New post: What happens when you run a query in Athena
  posts/what-happens-athena-query/images/csv-column.png
  posts/what-happens-athena-query/images/excel.png
  posts/what-happens-athena-query/index.md
Labels: Blog, ready for one-step review

#468 First Draft of "Using the AWS Parameters and Secrets Lambda Extension with Python, a practical example"
  posts/parameters-and-secrets-lambda-extension-with-python/images/choosing-the-extension.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/correct-region.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/iam-permission-json.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/lambda-code-deployed.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/lambda-configuration.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/lambda-function-setup.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/layers-box-empty.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/secret-created.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/secret-key-value.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/secret-name-description.png
  posts/parameters-and-secrets-lambda-extension-with-python/images/success.png
  posts/parameters-and-secrets-lambda-extension-with-python/index.md
Labels: community contribution

#501 New post: Transforming AWS API Gateway Access Log Into Prometheus Metrics
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/architecture.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/create-cwl-subsription-filter-02.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/create-cwl-subsription-filter.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/enable-access-log-for-http-api.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/enable-access-log-for-rest-api.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/grafana-dashboard.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/lambda-function-resource-based-policy.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/prometheus-query-result.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/request-latency.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/request-rate-by-api-key.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/request-rate-by-status.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/top-error-requests.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/top-highest-error-rate-by-api-key.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/images/top-slowest-requests.png
  posts/transforming-amazon-api-gateway-access-log-into-prometheus-metrics/index.md
Labels: ready for review, community contribution

#448 New post: Optimizing Performance and Cost with Multi-AZ Architecture - Guidelines for Multi-Account Environments
  posts/improving-availability-and-performance-with-multi-az-architecture/images/AZ-aware-load-balancing-scenario.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Availability-Zone-Name.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Availability-Zone-Name–Availability-Zone-ID-mapping-example.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Determining-the-AZ-IDs.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/East-West-VPC-to-VPC-traffic-inspection-scenario.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Multi-Account-Multi-VPC-deployment-architecture.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Return-traffic-flow-to-the-Application-Server.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Routing-traffic-through-NAT-Gateway.png
  posts/improving-availability-and-performance-with-multi-az-architecture/images/Traffic-flow-from-the-application-server-to-the-domain-controller.png
  posts/improving-availability-and-performance-with-multi-az-architecture/index.md
Labels: accepted, final review, Blog, recreated-pr

#410 New post: When should i failover
  posts/when-should-i-failover/images/alarm-DeepHealthCheckFailure.png
  posts/when-should-i-failover/images/alarm-LowOrderValueAlarm.png
  posts/when-should-i-failover/images/application-architecture-with-observability-components.png
  posts/when-should-i-failover/images/business-metric.png
  posts/when-should-i-failover/images/deep-healthcheck-metric.png
  posts/when-should-i-failover/images/failover-initiated.png
  posts/when-should-i-failover/images/multi-region-application-architecture.png
  posts/when-should-i-failover/images/normal-state-after-failover.png
  posts/when-should-i-failover/images/overall-dashboard-normal-state.png
  posts/when-should-i-failover/images/service-metrics.png
  posts/when-should-i-failover/index.md
Labels: Blog, ready for editorial review, technical review complete, recreated-pr

#499 New Tutorial: Synchronous Request-Response with Amazon API Gateway and AWS Lambda
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/diagram-api-gw-lambda.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-confirm-permissions.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-empty-asset-bucket.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-integrated-test-response.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-invoke-backend-url.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-invoke-url.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-lambda-integration.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-lambda-source-code.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-new-stack.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-redirect-integration.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/images/screen-simple-api.png
  tutorials/application-integration-patterns/request-response-with-api-gateway/index.md
Labels: tutorial, ready for technical review

#446 New post: Deploy a Java Application on Linux
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/PCG-1-lightsail.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-1.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-10.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-11.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-2.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-3.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-4.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-5.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-6.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-7.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-8.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-networking-9.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-1.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-2.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-3.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-4.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-5.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-6.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-7.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-delete-1.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-linux-vps-delete-2.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-2.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-3.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-4.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-5.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-linux-1.1.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-linux-1.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/lightsail-s3-bucket-linux-2.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/s3-delete-1.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/s3-delete-2.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/images/s3-delete-3.png
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
Labels: changes requested, final review, tutorial

#460 New post: A Gentle Introduction to Transformer Architecture and Relevance to Generative AI
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/Auto_CoT.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/CoT-SC.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/CoT.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/Feed-Forward Neural Network.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/GenAI_Customization-summary.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/GenAI_Customization.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/LLM-models.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/RLHF.jpg
  posts/a-gentle-intro-to-transformer-and-gen-ai/images/ToT.png
  posts/a-gentle-intro-to-transformer-and-gen-ai/index.md
Labels: final review, Blog, technical review complete, editorial review complete

#525 Fix: Fixing relative link, adding series ToC
  tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
  tutorials/practical-cloud-guide/series.md
Labels: bug

#531 Moving to a new PR as we couldn't edit
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure1.jpeg
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure10-stream-store-per-project.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure11-geo-replication.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure12-scalingstorage.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure13-unidirectionalflow.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure14-buildvsbuy.jpeg
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure2-hard-drive.jpeg
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure3-perishableinsights-forrester.jpg
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure4-siloed-architecture.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure5-batch-vs-realtime.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure6-realtime-streaming.jpg
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure7-streamstorequeue.jpg
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure8-constructs.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/images/Figure9-cdc.png
  posts/six-things-to-consider-when-moving-from-batch-to-real-time-data-stream-processing/index.md
Labels: Blog, one-step review complete

#433 New post: What Happened to my Car? Understanding Gray Failures
  posts/what-happened-to-my-car/images/AdobeStock_290434377.jpeg
  posts/what-happened-to-my-car/index.md
Labels: accepted, Blog, ready for editorial review, technical review complete

#496 New post: Ingesting Data into OpenSearch using Apache Kafka and Go
  tutorials/opensearch-kafka-golang-data-ingestion/images/aoss.jpg
  tutorials/opensearch-kafka-golang-data-ingestion/images/arch.jpg
  tutorials/opensearch-kafka-golang-data-ingestion/images/cloud9.png
  tutorials/opensearch-kafka-golang-data-ingestion/images/msk-cluster.jpg
  tutorials/opensearch-kafka-golang-data-ingestion/images/query-all.png
  tutorials/opensearch-kafka-golang-data-ingestion/images/query-fields.jpg
  tutorials/opensearch-kafka-golang-data-ingestion/images/query-term-fields.jpg
  tutorials/opensearch-kafka-golang-data-ingestion/images/query-term.jpg
  tutorials/opensearch-kafka-golang-data-ingestion/images/rule.png
  tutorials/opensearch-kafka-golang-data-ingestion/index.md
Labels: tutorial, ready for editorial review, technical review complete

#541 New Blog Post: Where do I put my backups in the cloud?
  posts/where-do-i-put-my-backups-in-the-cloud/images/multi-account.png
  posts/where-do-i-put-my-backups-in-the-cloud/images/multi-region.png
  posts/where-do-i-put-my-backups-in-the-cloud/images/single-region.png
  posts/where-do-i-put-my-backups-in-the-cloud/index.md
Labels: Blog, ready for editorial review, technical review complete

#417 New Post: Set Up and Configure Microsoft PKI for Smart Card Authentication with Amazon WorkSpaces
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/01_high-level-architecture-connectivity-process-amazon-workspaces-with-smart-card.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/02-additional-capability-before-deploying-cloudformation-stack.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/03-auto-enrollment--certificates-service-client.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/04-domain-personal-certificate.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/05-general-tab-certificate-template.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/06-object-types-for-searching.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/07-adding-read-enroll-permissions.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/08-publishing-sample-certificate-template.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/09-adding-OCSP-url-into-ca.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/10-properties-on-CA.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/11-Select-CA-Certificate-Location.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/12-Choose-CA-Certificate-Add-Revocation-Configuration-wizard.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/13-select-a-Certification-Authority.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/14-Select-Signing-Certificate.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/15-OCSP-Location-pkivew-msc.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/16-sample-output-tnc-command-against-OCSP-URL.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/17-Delegation-sample-AD-user-dsa-msc.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/18-add-services-window-kerberoscd.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/19-Request-Handling-Tab.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/20-Cryptography-tab-creating-new-Certificate-Template.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/21-Security-tab-when-creating-Certificate-Template.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/22-successful-sample-output-certutil-scinfo-command.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/23-Request-Certificates-window-selecting-SmartcardWS-template.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/24-prompt-enter-authentication-PIN-the-smart-card.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/25-successful-request-certificate-successful-installation-certificate-onto-the-smart-card.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/26-Personal-certificate-store.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/27-URL-Retrieval-Tool.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/28-URL-Retrieval-Tool-with-an-entry-showing-the-status-Verified.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/29-Group-Policy-Management.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/30-smart-card-user-certificate-and-the-full-certificate-path.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/31-Trusted-Root-Certification-Authorities.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/32-Intermediate-Certification-Authorities.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/33-Register-a-certificate.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/34-WorkSpaces-Client-with-Certificate-Dialog.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/35-WorkSpaces-Client-with-Certificate-Dialog-prompt.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/36-WorkSpaces-Client-Windows-logon-screen.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/37-Microsoft-Remote-Desktop-Connection.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/38-Windows-Security-prompt-requesting-smart-card-PIN.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/39-WorkSpaces-Client-at-the-Linux-logon-page.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/40-WorkSpaces-client-returning-Unknown-Error-Occurred.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/41-Windows-logon-page-returning-Signing-smart-card-is-not-supported.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/42-Linux-logon-page-returning-Sorry-that-did-not-work.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/43-WorkSpaces-client-returning-Unable-to-sign-in.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/images/44-General-Tab.png
  tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
Labels: tutorial, ready for editorial review, technical review complete, recreated-pr

#431 New post: Building Rust Applications For AWS Graviton
  tutorials/building-rust-applications-for-aws-graviton/images/dynamo-setup.jpg
  tutorials/building-rust-applications-for-aws-graviton/index.md
Labels: tutorial, ready for editorial review, technical review complete, editorial review complete

#526 New post : Enhancing decision making with k-Nearest Neighbors with Amazon SageMaker
  posts/knn-with-amazon-sagemaker/images/01.png
  posts/knn-with-amazon-sagemaker/images/02.png
  posts/knn-with-amazon-sagemaker/images/03.png
  posts/knn-with-amazon-sagemaker/images/04.png
  posts/knn-with-amazon-sagemaker/images/05.png
  posts/knn-with-amazon-sagemaker/images/06.png
  posts/knn-with-amazon-sagemaker/images/07.png
  posts/knn-with-amazon-sagemaker/images/08.png
  posts/knn-with-amazon-sagemaker/images/09.png
  posts/knn-with-amazon-sagemaker/images/10.png
  posts/knn-with-amazon-sagemaker/images/11.png
  posts/knn-with-amazon-sagemaker/images/12.png
  posts/knn-with-amazon-sagemaker/images/13.png
  posts/knn-with-amazon-sagemaker/images/14.png
  posts/knn-with-amazon-sagemaker/images/15.png
  posts/knn-with-amazon-sagemaker/images/16.png
  posts/knn-with-amazon-sagemaker/images/17.png
  posts/knn-with-amazon-sagemaker/images/18.png
  posts/knn-with-amazon-sagemaker/images/19.png
  posts/knn-with-amazon-sagemaker/images/20.png
  posts/knn-with-amazon-sagemaker/images/21.png
  posts/knn-with-amazon-sagemaker/images/22.png
  posts/knn-with-amazon-sagemaker/images/23.png
  posts/knn-with-amazon-sagemaker/images/24.png
  posts/knn-with-amazon-sagemaker/index.md
Labels: Blog, ready for one-step review

#521 New post: Stateless Isn’t Always the Answer. Building Stateful Actor Services on AWS
  posts/building-stateful-actor-services-on-aws/index.md
Labels: editorial review in progress, Blog, technical review complete

#561 Build a ChatGPT-powered AI tool to cut the fluff from YouTube videos
  tutorials/build-ai-with-hf-chatgpt/images/intro-01.gif
  tutorials/build-ai-with-hf-chatgpt/images/part1-01.gif
  tutorials/build-ai-with-hf-chatgpt/images/part1-02.jpg
  tutorials/build-ai-with-hf-chatgpt/images/part2-01.jpg
  tutorials/build-ai-with-hf-chatgpt/images/part2-02.png
  tutorials/build-ai-with-hf-chatgpt/images/part2-03.png
  tutorials/build-ai-with-hf-chatgpt/images/part4-01.png
  tutorials/build-ai-with-hf-chatgpt/index.md
Labels: tutorial

#459 fix-gray-failures-fast-using-automation-and-route53-arc-zonal-shift
  posts/fix-gray-failures-fast-using-automation-and-route53-arc-zonal-shift/images/after-zonal-shift.png
  posts/fix-gray-failures-fast-using-automation-and-route53-arc-zonal-shift/images/before-zonal-shift.png
  posts/fix-gray-failures-fast-using-automation-and-route53-arc-zonal-shift/images/diff_observ.png
  posts/fix-gray-failures-fast-using-automation-and-route53-arc-zonal-shift/images/zonal-shift-sample-solution.png
  posts/fix-gray-failures-fast-using-automation-and-route53-arc-zonal-shift/index.md
Labels: Blog

#432 New post: Search and Analyze data in Amazon OpenSearch using SQL
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_01.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_02.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_03.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_04.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_05.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_06.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_07.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_08.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_09.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_10.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_11.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_12.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_13.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_14.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/images/image_15.png
  tutorials/search-analyze-using-sql-with-amazon-opensearch/index.md
Labels: tutorial, ready for editorial review, technical review complete

#413 New post: What is Cloud Storage
  posts/what-is-cloud-storage/images/thumbdrive.jpeg
  posts/what-is-cloud-storage/index.md
Labels: changes requested, Blog, recreated-pr

#473 New post: The Power of Generative AI in Retail Industry
  posts/the-power-of-generative-ai-in-retail-industry/images/Architecture1.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Architecture2.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Architecture3.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image1.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image3.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image4.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image5.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image6.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image7.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Image8.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Picture2.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Picture3.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Picture4.png
  posts/the-power-of-generative-ai-in-retail-industry/images/Picture6.gif
  posts/the-power-of-generative-ai-in-retail-industry/index.md
Labels: editorial review in progress, Blog, technical review complete

#573 A Tool to Validate AWS IoT Rules SQL Statements
  posts/validation-tool-for-aws-iot-rules/images/architecture.png
  posts/validation-tool-for-aws-iot-rules/images/example-failure.png
  posts/validation-tool-for-aws-iot-rules/images/repo.png
  posts/validation-tool-for-aws-iot-rules/index.md
Labels: Blog, ready for one-step review

#518 New post: Can I run existing Go applications on AWS Lambda? (Part 2)
  tutorials/golang-and-aws-lambda/01-golang-apis-on-aws-lambda/index.md
  tutorials/golang-and-aws-lambda/02-golang-gin-app-on-aws-lambda/images/arch.jpg
  tutorials/golang-and-aws-lambda/02-golang-gin-app-on-aws-lambda/images/cfn.png
  tutorials/golang-and-aws-lambda/02-golang-gin-app-on-aws-lambda/images/dynamodb-records.jpg
  tutorials/golang-and-aws-lambda/02-golang-gin-app-on-aws-lambda/index.md
  tutorials/golang-and-aws-lambda/series.md
Labels: changes requested, tutorial, editorial review complete, ready for one-step review

#534 New post: Build Your Own Recommendation Engine for a Streaming Platform Clone on AWS: A Full Stack Series
  tutorials/recommendation-engine-full-stack/images/SetupUI.jpg
  tutorials/recommendation-engine-full-stack/images/augmented_dateset.png
  tutorials/recommendation-engine-full-stack/images/binning_runtimeminutes.png
  tutorials/recommendation-engine-full-stack/images/boxplot_iqr_outliers.png
  tutorials/recommendation-engine-full-stack/images/byom.jpg
  tutorials/recommendation-engine-full-stack/images/chaliceSetup.png
  tutorials/recommendation-engine-full-stack/images/cloud9.png
  tutorials/recommendation-engine-full-stack/images/cloud9gear.png
  tutorials/recommendation-engine-full-stack/images/clusternumber.png
  tutorials/recommendation-engine-full-stack/images/customscalingdeployment.png
  tutorials/recommendation-engine-full-stack/images/elbow.png
  tutorials/recommendation-engine-full-stack/images/finalnumericalfeatures.png
  tutorials/recommendation-engine-full-stack/images/kmeans.png
  tutorials/recommendation-engine-full-stack/images/myflix1.png
  tutorials/recommendation-engine-full-stack/images/myflix2.jpg
  tutorials/recommendation-engine-full-stack/images/myflix3.jpg
  tutorials/recommendation-engine-full-stack/images/onehotencoded.png
  tutorials/recommendation-engine-full-stack/images/rawmovie_initialstructure.png
  tutorials/recommendation-engine-full-stack/images/recommendation_flow.png
  tutorials/recommendation-engine-full-stack/images/s3bucket_data.png
  tutorials/recommendation-engine-full-stack/images/sagemaker-deployedendpoints.png
  tutorials/recommendation-engine-full-stack/images/sklearnscaledvalues.png
  tutorials/recommendation-engine-full-stack/index.md
Labels: final review, tutorial, technical review complete, editorial review complete

#551 New post: Using Amazon SageMaker to Optimize Compilation and Training for Open Source GPT-2 Model
  posts/llm-compiler-optimization-gpt2/images/how-does-xla-work-1.png
  posts/llm-compiler-optimization-gpt2/images/load-dataset-1.png
  posts/llm-compiler-optimization-gpt2/images/result-training-cost-1.png
  posts/llm-compiler-optimization-gpt2/images/result-training-data-throught-1.png
  posts/llm-compiler-optimization-gpt2/images/result-training-loss-1.png
  posts/llm-compiler-optimization-gpt2/images/result-training-time-1.png
  posts/llm-compiler-optimization-gpt2/images/training-compiler-1.png
  posts/llm-compiler-optimization-gpt2/index.md
Labels: editorial review in progress, foundational, technical review complete
