Repository build-on-aws/content, pull requests merged in 2023-08, with the labels that each got.

#602 New Post: How to Use Proprietary Foundation Models with Amazon SageMaker JumpStart for Building Generative AI Applications
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-generative-ai-sagemaker-1.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-jumpstart-ai21-2.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-jumpstart-cohere-command-model-marketplace.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-jumpstart-cohere-command-model-playglound.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-jumpstart-cohere-command-model.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-jumpstart-cohere-command-studio.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/2023-jumpstart-proprietary.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/ML-12633-image001.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/images/sagemaker-jumpstart-propritary-models.jpg
  posts/using-proprietary-foundation-models-sagemaker-jumpstart-building-gen-ai-apps/index.md
Labels: Blog

#488 New post- Practical cloud guide: Restore a sql server database
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-1.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-2.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-3.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-4.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-5.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-6.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/cloud9-environment-delete.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/delete-disk-1.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/delete-disk-2.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/delete-vps-1.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/delete-vps-2.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/rdp-1.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-1.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-2.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-3.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-4.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-5.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-6.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/sqlserver-studio-7.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/images/ssms-1.png
  posts/practical-cloud-guide/migrate-a-sql-server-database-in-the-cloud/index.md
Labels: final review, tutorial, technical review complete, editorial review complete

#617 New post - Prompt Engineering for Developers: How AI Can Help With Architecture Decisions
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/clarify_requirements.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/decision_record.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/generic.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/other_options.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/priming_context.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/priming_role.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/pros_and_cons.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/recommendation.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/requirements_list.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/images/with_context.png
  posts/prompt-engineering-for-developers/how-ai-can-help-with-architecture-decisions/index.md
Labels: ready for technical review, Quick guide

#489 New post- Practical cloud guide: Deploy a cloud database to scale LAMP app
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/add-task.jpg
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/lamp-architecture-1.jpg
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/lamp-architecture-2.jpg
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/lamp-architecture-3.jpg
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/save_settings.jpg
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/scaled-app.png
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/images/todo_settings.jpg
  tutorials/practical-cloud-guide/deploy-a-cloud-database-to-scale-lamp-app/index.md
Labels: changes requested, tutorial, technical review complete

#613 Building Go Applications For AWS Graviton
  tutorials/building-go-applications-for-aws-graviton/images/dynamo-setup.jpg
  tutorials/building-go-applications-for-aws-graviton/index.md
Labels: tutorial, ready for technical review

#622 New Post: Scaling your application: Data patterns to enable reliability and flexibility
  posts/scaling-your-application-data-patterns/images/cqrs.png
  posts/scaling-your-application-data-patterns/images/eventbridge.png
  posts/scaling-your-application-data-patterns/index.md
Labels: blog, ready for one-step review

#614 New post: The ABCs of Generative AI - update
  posts/the-abcs-of-generative-ai/images/ABCsGenAIheader.gif
  posts/the-abcs-of-generative-ai/images/a.png
  posts/the-abcs-of-generative-ai/images/b.png
  posts/the-abcs-of-generative-ai/images/c.png
  posts/the-abcs-of-generative-ai/images/d.png
  posts/the-abcs-of-generative-ai/images/e.png
  posts/the-abcs-of-generative-ai/images/f.png
  posts/the-abcs-of-generative-ai/images/g.png
  posts/the-abcs-of-generative-ai/images/h.png
  posts/the-abcs-of-generative-ai/images/i.png
  posts/the-abcs-of-generative-ai/images/j.png
  posts/the-abcs-of-generative-ai/images/k.png
  posts/the-abcs-of-generative-ai/images/l.png
  posts/the-abcs-of-generative-ai/images/m.png
  posts/the-abcs-of-generative-ai/images/n.png
  posts/the-abcs-of-generative-ai/images/o.png
  posts/the-abcs-of-generative-ai/images/p.png
  posts/the-abcs-of-generative-ai/images/q.png
  posts/the-abcs-of-generative-ai/images/r.png
  posts/the-abcs-of-generative-ai/images/s.png
  posts/the-abcs-of-generative-ai/images/t.png
  posts/the-abcs-of-generative-ai/images/u.png
  posts/the-abcs-of-generative-ai/images/v.png
  posts/the-abcs-of-generative-ai/images/w.png
  posts/the-abcs-of-generative-ai/images/x.png
  posts/the-abcs-of-generative-ai/images/y.png
  posts/the-abcs-of-generative-ai/images/z.png
  posts/the-abcs-of-generative-ai/index.md
Labels: ready to be published, fundamentals, technical review complete, editorial review complete, gen-ai

#600 New post: Bring your own machine learning code to aws
  posts/bring-your-own-machine-learning-code-to-aws/images/data_import.png
  posts/bring-your-own-machine-learning-code-to-aws/images/data_preprocess.png
  posts/bring-your-own-machine-learning-code-to-aws/images/decision_tree.png
  posts/bring-your-own-machine-learning-code-to-aws/images/methods.png
  posts/bring-your-own-machine-learning-code-to-aws/images/ml_lifecycle.png
  posts/bring-your-own-machine-learning-code-to-aws/index.md
Labels: quick guide

#639 How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/1hr7d54qb5ifq9xe7gai.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/3rqufqes4lo7aanfz5dg.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/API-Lambda-nueva.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/API-Lambda-original.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/bd32ssu76qao4ja9rwh1.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/e3sgizn3phj383el2qog.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/fbar48yg8vecdus7mxcp.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/jmaxniwf3yy93uq1iaqn.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/kvg281vkq9m3h3weyt30.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/md84up7w4hzh5dej33um.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/phtolaebnjjdwrl3ueor.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/pr8lm14864prsmawh5ee.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/rm4x6cpvgnd6ghyvraog.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/trf0vwnr8lg7877na0pz.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/uz4mhuqzhscs8y4wy8gj.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/v1pserwls9iff098n0a7.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/images/vmlo90ybylgx35a6jcmb.png
  posts/How-to-tackle-time-out-on-api-gateway-using-step-functions-and-SAM/index.md
Labels: community contribution, ready for one-step review

#601 Zero data loss disaster recovery using amazon rds
  posts/zero-dataloss-dr-using-rds/images/pic12_disaster_blast_radius.jpg
  posts/zero-dataloss-dr-using-rds/images/pic14_3_way_az.jpg
  posts/zero-dataloss-dr-using-rds/images/pic1_enabled_vs_native.jpg
  posts/zero-dataloss-dr-using-rds/images/pic2_az_clustered.jpg
  posts/zero-dataloss-dr-using-rds/images/pic2_az_ebs.jpg
  posts/zero-dataloss-dr-using-rds/images/pic5_recovery_rds.jpg
  posts/zero-dataloss-dr-using-rds/images/pic6_recovery_aurora.jpg
  posts/zero-dataloss-dr-using-rds/images/pic8_backup_workflow.jpg
  posts/zero-dataloss-dr-using-rds/images/pic9_replication_sync_vs_async.jpg
  posts/zero-dataloss-dr-using-rds/index.md
Labels: ready to be published, blog, ready for one-step review

#598 New post: Fast Pre-trained Model Deployment - The code only approach
  posts/fast-pre-trained-model-deployment-the-code-only-approach/index.md
Labels: ready to be published, blog, ready for one-step review

#635 New post: Create and run SageMaker pipelines using AWS SDKs
  posts/create-and-run-sagemaker-pipelines-using-aws-sdks/images/Pipeline.PNG
  posts/create-and-run-sagemaker-pipelines-using-aws-sdks/images/SagemakerCode.PNG
  posts/create-and-run-sagemaker-pipelines-using-aws-sdks/images/Workflow.PNG
  posts/create-and-run-sagemaker-pipelines-using-aws-sdks/index.md
Labels: blog, ready for one-step review

#612 New post: Coding Publish and Subscribe Using SNS, SQS, and the AWS SDKs
  posts/topics_and_queues_workflow_with_sdks/images/fifo_topics_diagram.jpg
  posts/topics_and_queues_workflow_with_sdks/index.md
Labels: published, quick guide

#630 Build your own knowledge base with multilingual Q&A powered by generative AI
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/domain_and_user_profile.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_01.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_02.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_03.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_04.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_05.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_06.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/fig_7.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/flan_ul2_search.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/jumpstart_menu.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/jupyter_notebook.jpg
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/sagemaker_console.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/images/sagemaker_domain.png
  tutorials/build-a-knowledge-base-with-multilingual-q-and-a-gen-ai/index.md
Labels: final review, tutorial, gen-ai

#650 How to maximize application uptime using CloudWatch anomaly detection
  posts/max-uptime-cloudwatch-anomaly-detection/images/image.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image1.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image2.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image3.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image4.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image5.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image6.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image7.png
  posts/max-uptime-cloudwatch-anomaly-detection/images/image8.png
  posts/max-uptime-cloudwatch-anomaly-detection/index.md
Labels: community contribution, ready for one-step review

#659 Why Engineers Hold The Keys
  posts/why-engineers-hold-the-keys/images/aws-cost-optimization.jpg
  posts/why-engineers-hold-the-keys/images/budgets.png
  posts/why-engineers-hold-the-keys/images/cost-explorer.png
  posts/why-engineers-hold-the-keys/images/s3-intelligent-tiering.png
  posts/why-engineers-hold-the-keys/index.md
Labels: blog, ready for one-step review

#681 adding cost wave and spaces information to graviton tutorials
  tutorials/building-go-applications-for-aws-graviton/index.md
  tutorials/building-rust-applications-for-aws-graviton/index.md
Labels: ready for one-step review

#665 New post: Jira tix comprehend
  posts/comprehend-jira-tickets/images/Entities.jpg
  posts/comprehend-jira-tickets/images/GetStarted.jpg
  posts/comprehend-jira-tickets/images/JsonExampleCleaned.jpg
  posts/comprehend-jira-tickets/images/KeyPhrasesExample.jpg
  posts/comprehend-jira-tickets/images/S3.jpg
  posts/comprehend-jira-tickets/images/ScheduledJobOutput.jpg
  posts/comprehend-jira-tickets/images/analysis02.jpg
  posts/comprehend-jira-tickets/images/analysis02.png
  posts/comprehend-jira-tickets/images/analysis03.jpg
  posts/comprehend-jira-tickets/images/analysisJobsExample.jpg
  posts/comprehend-jira-tickets/images/analysist01.jpg
  posts/comprehend-jira-tickets/images/analyticJob.jpg
  posts/comprehend-jira-tickets/images/dataSample.jpg
  posts/comprehend-jira-tickets/images/sampleCleanData.jpg
  posts/comprehend-jira-tickets/images/tarFile.jpg
  posts/comprehend-jira-tickets/index.md
Labels: blog, community contribution, ready for one-step review

#587 New post: From Cloud Chaos to Cost Control
  posts/from-cloud-chaos-to-cost-control/images/Cost_Anomaly_Detection.png
  posts/from-cloud-chaos-to-cost-control/images/alert_subscription.png
  posts/from-cloud-chaos-to-cost-control/images/cost_anomaly_10a.png
  posts/from-cloud-chaos-to-cost-control/images/cost_monitor.png
  posts/from-cloud-chaos-to-cost-control/index.md
Labels: blog, ready for one-step review

#693 [New Tutorial] EKS tutorial high-traffic site
  tutorials/eks-cluster-high-traffic/index.md
Labels: published, tutorial, technical review complete, editorial review complete

#699 New post: Sphinx documentation pipeline
  posts/automatically-release-sphinx-documentation-cdk-pipelines-custom-codebuild-image/images/sphinx-documentation-architecture.svg
  posts/automatically-release-sphinx-documentation-cdk-pipelines-custom-codebuild-image/images/sphinx-documentation.png
  posts/automatically-release-sphinx-documentation-cdk-pipelines-custom-codebuild-image/images/sphinx-s3-content.png
  posts/automatically-release-sphinx-documentation-cdk-pipelines-custom-codebuild-image/index.md
Labels: published, blog, community contribution, ready for one-step review

#651 New post: The ultimate guideline for running Spark on AWS in maintainable, reliable and cost-effective way
  posts/ultimate-guideline-for-running-spark-on-aws/images/spark-aws.png
  posts/ultimate-guideline-for-running-spark-on-aws/images/why-aws.png
  posts/ultimate-guideline-for-running-spark-on-aws/index.md
Labels: published

#696 [New Tutorial] EKS tutorial for scalable IPv6
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_connect_dialog.png
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_instance_ssh_terminal_view.png
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_instance_successful_launch.png
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_launch_instance.png
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_launch_instance_networking.png
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_list_bastion_selected.png
  tutorials/eks-cluster-ipv6-globally-scalable/images/ec2_proceed_without_keypair.png
  tutorials/eks-cluster-ipv6-globally-scalable/index.md
Labels: published, tutorial, technical review complete, editorial review complete

#695 [New Tutorial] EKS tutorial load-balanced ipv6
  tutorials/eks-cluster-load-balancer-ipv6/index.md
Labels: published, tutorial, technical review complete, editorial review complete

#694 [New Tutorial] EKS tutorial load-balanced ipv4
  tutorials/eks-cluster-load-balancer-ipv4/images/2048_game.png
  tutorials/eks-cluster-load-balancer-ipv4/index.md
Labels: published, tutorial, technical review complete, editorial review complete

#619 [New Post]: Levelling up Your Releases: Reduce Risk with Blue/Green Deployments
  posts/levelling-up-your-releases-a-deep-dive-into-blue-green-deployments/images/api-gateway-canary-releases.png
  posts/levelling-up-your-releases-a-deep-dive-into-blue-green-deployments/images/blue-green-codedeploy.png
  posts/levelling-up-your-releases-a-deep-dive-into-blue-green-deployments/images/swap-auto-scaling-group.png
  posts/levelling-up-your-releases-a-deep-dive-into-blue-green-deployments/index.md
Labels: blog, ready for one-step review

#631 Practical Cloud Guide: Understanding Identity and Access Management (IAM) From the Ground Up
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/console-1.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/console-2.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/console-3.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/identities.jpg
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/s3-1.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/s3-2.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/s3-3.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/images/s3-4.png
  tutorials/practical-cloud-guide/learning-aws-iam-by-writing-your-first-policies-for-groups-and-users/index.md
  tutorials/practical-cloud-guide/series.md
Labels: published, editorial review in progress, tutorial, technical review complete

#682 New post: AI-Powered Development: Creating Secure and Resilient Apps with CodeWhisperer and CodeGuru
  posts/ai-powered-development-secure-resilient-apps-codewhisperer-codeguru/images/codeguru-create-scan.png
  posts/ai-powered-development-secure-resilient-apps-codewhisperer-codeguru/images/codeguru-dashboard.png
  posts/ai-powered-development-secure-resilient-apps-codewhisperer-codeguru/images/codeguru-findings.png
  posts/ai-powered-development-secure-resilient-apps-codewhisperer-codeguru/images/codeguru-pipeline-integrations.png
  posts/ai-powered-development-secure-resilient-apps-codewhisperer-codeguru/images/codewhisperer-security-scan.png
  posts/ai-powered-development-secure-resilient-apps-codewhisperer-codeguru/index.md
Labels: blog, ready for one-step review
