Repository build-on-aws/content, pull requests merged in 2023-12, with the labels that each got.

#929 [New Post] How To Choose Your LLM
  posts/how-to-choose-your-llm/images/df_tokens_completion.png
  posts/how-to-choose-your-llm/images/df_tokens_prompt.jpg
  posts/how-to-choose-your-llm/images/fig_01.png
  posts/how-to-choose-your-llm/images/fig_02.png
  posts/how-to-choose-your-llm/images/fig_03.png
  posts/how-to-choose-your-llm/images/fig_04.png
  posts/how-to-choose-your-llm/images/fig_05.jpg
  posts/how-to-choose-your-llm/images/gif_01.gif
  posts/how-to-choose-your-llm/images/gif_02.gif
  posts/how-to-choose-your-llm/index.md
Labels: blog, ready for one-step review

#915 [New tutorial] Sending Events from DynamoDB using Eventbridge Pipes
  tutorials/ddb-streams-to-eb-pipes/images/createddbitem.png
  tutorials/ddb-streams-to-eb-pipes/images/createrules1.png
  tutorials/ddb-streams-to-eb-pipes/images/createrules2.png
  tutorials/ddb-streams-to-eb-pipes/images/createrules3.png
  tutorials/ddb-streams-to-eb-pipes/images/createtable.png
  tutorials/ddb-streams-to-eb-pipes/images/ebpipe.png
  tutorials/ddb-streams-to-eb-pipes/images/ebpipes-ddbstreams-diagram.jpg
  tutorials/ddb-streams-to-eb-pipes/images/enablestreams.png
  tutorials/ddb-streams-to-eb-pipes/images/eventinlog.png
  tutorials/ddb-streams-to-eb-pipes/images/filtering.png
  tutorials/ddb-streams-to-eb-pipes/images/pipetarget.png
  tutorials/ddb-streams-to-eb-pipes/images/ruledescription.png
  tutorials/ddb-streams-to-eb-pipes/images/rules.png
  tutorials/ddb-streams-to-eb-pipes/images/transformer.png
  tutorials/ddb-streams-to-eb-pipes/index.md
Labels: tutorial, technical review complete, ready for final review, editorial re-review complete

#963 [New post] Handling streaming and structured data using Amazon Bedrock
  posts/Handling-streaming-and-structured-data-using-amazon-bedrock/index.md
Labels: blog, ready for one-step review

#876 [LIVE STREAM] This is an existing show to be added to the community page
  livestreams/lets-talk-about-data/2023-04-05/images/show1.jpg
  livestreams/lets-talk-about-data/2023-04-05/index.md
  livestreams/lets-talk-about-data/2023-04-12/images/show2.jpg
  livestreams/lets-talk-about-data/2023-04-12/index.md
  livestreams/lets-talk-about-data/2023-04-19/images/show3.jpg
  livestreams/lets-talk-about-data/2023-04-19/index.md
  livestreams/lets-talk-about-data/2023-04-26/images/show4.jpg
  livestreams/lets-talk-about-data/2023-04-26/index.md
  livestreams/lets-talk-about-data/2023-05-03/images/show5.jpg
  livestreams/lets-talk-about-data/2023-05-03/index.md
  livestreams/lets-talk-about-data/2023-05-17/images/show6.jpg
  livestreams/lets-talk-about-data/2023-05-17/index.md
  livestreams/lets-talk-about-data/2023-05-24/images/show7.jpg
  livestreams/lets-talk-about-data/2023-05-24/index.md
  livestreams/lets-talk-about-data/2023-06-14/images/show8.jpg
  livestreams/lets-talk-about-data/2023-06-14/index.md
  livestreams/lets-talk-about-data/2023-06-23/images/show9.jpg
  livestreams/lets-talk-about-data/2023-06-23/index.md
  livestreams/lets-talk-about-data/2023-06-28/images/show10.jpg
  livestreams/lets-talk-about-data/2023-06-28/index.md
  livestreams/lets-talk-about-data/2023-07-05/images/show11.jpg
  livestreams/lets-talk-about-data/2023-07-05/index.md
  livestreams/lets-talk-about-data/2023-07-12/images/show12.jpg
  livestreams/lets-talk-about-data/2023-07-12/index.md
  livestreams/lets-talk-about-data/2023-07-19/images/show13.jpg
  livestreams/lets-talk-about-data/2023-07-19/index.md
  livestreams/lets-talk-about-data/2023-07-26/images/show14.jpg
  livestreams/lets-talk-about-data/2023-07-26/index.md
  livestreams/lets-talk-about-data/2023-08-02/images/show15.jpg
  livestreams/lets-talk-about-data/2023-08-02/index.md
  livestreams/lets-talk-about-data/2023-08-09/images/show16.jpg
  livestreams/lets-talk-about-data/2023-08-09/index.md
  livestreams/lets-talk-about-data/2023-08-16/images/show17.jpg
  livestreams/lets-talk-about-data/2023-08-16/index.md
  livestreams/lets-talk-about-data/2023-08-23/images/show18.jpg
  livestreams/lets-talk-about-data/2023-08-23/index.md
  livestreams/lets-talk-about-data/2023-08-30/images/show19.jpg
  livestreams/lets-talk-about-data/2023-08-30/index.md
  livestreams/lets-talk-about-data/2023-09-06/images/show20.jpg
  livestreams/lets-talk-about-data/2023-09-06/index.md
  livestreams/lets-talk-about-data/2023-09-13/images/show21.jpg
  livestreams/lets-talk-about-data/2023-09-13/index.md
  livestreams/lets-talk-about-data/2023-09-20/images/show22.jpg
  livestreams/lets-talk-about-data/2023-09-20/index.md
  livestreams/lets-talk-about-data/2023-09-27/images/show23.jpg
  livestreams/lets-talk-about-data/2023-09-27/index.md
  livestreams/lets-talk-about-data/2023-10-04/images/show24.jpg
  livestreams/lets-talk-about-data/2023-10-04/index.md
  livestreams/lets-talk-about-data/2023-10-11/images/show25.jpg
  livestreams/lets-talk-about-data/2023-10-11/index.md
  livestreams/lets-talk-about-data/2023-10-18/images/show26.jpg
  livestreams/lets-talk-about-data/2023-10-18/index.md
  livestreams/lets-talk-about-data/2023-10-25/images/show27.jpg
  livestreams/lets-talk-about-data/2023-10-25/index.md
  livestreams/lets-talk-about-data/images/AWS_Lets Talk About Data_Logo_DARK_Transparent.png
  livestreams/lets-talk-about-data/images/ltad-header.jpg
  livestreams/lets-talk-about-data/index.md
  spaces/livestreams/space.md
Labels: livestream

#960 [New post] Connecting Lightsail to AWS Services
  posts/connecting-lightsail-to-aws-services/images/peering-1.png
  posts/connecting-lightsail-to-aws-services/images/peering-2.png
  posts/connecting-lightsail-to-aws-services/images/peering-3.png
  posts/connecting-lightsail-to-aws-services/images/rds-1.png
  posts/connecting-lightsail-to-aws-services/images/rds-2.png
  posts/connecting-lightsail-to-aws-services/images/rds-3.png
  posts/connecting-lightsail-to-aws-services/images/rds-4.png
  posts/connecting-lightsail-to-aws-services/images/rds-5.png
  posts/connecting-lightsail-to-aws-services/images/rds-6.png
  posts/connecting-lightsail-to-aws-services/images/rds-7.png
  posts/connecting-lightsail-to-aws-services/images/test-1.png
  posts/connecting-lightsail-to-aws-services/images/test-2.png
  posts/connecting-lightsail-to-aws-services/images/test-3.png
  posts/connecting-lightsail-to-aws-services/images/test-4.png
  posts/connecting-lightsail-to-aws-services/images/vpc-peering-1.png
  posts/connecting-lightsail-to-aws-services/images/vpc-peering-2.png
  posts/connecting-lightsail-to-aws-services/images/vpc-peering-3.png
  posts/connecting-lightsail-to-aws-services/images/vpc-peering-4.png
  posts/connecting-lightsail-to-aws-services/index.md
Labels: blog, ready for one-step review

#970 [recovery] added table with sessions
  livestreams/recovery2023/images/hosts.webp
  livestreams/recovery2023/index.md
Labels: Draft

#955 [New tutorial] Real-Time Sentiment Analysis Using Apache Kafka and SageMaker Jupyter Notebooks
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/Aiven-service.webp
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/JumpStart.webp
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/create-domain.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/create-topics.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/delete-kafka.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/delete_endpoint.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/delete_endpoint_configuration.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/delete_model.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/deploy-model.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/enriched_data.webp
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/example_error_message.webp
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/load-certificates.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/open-notebook.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/open_studio.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/result.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/select-model.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/topic-messages.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/images/topics.png
  posts/real-time-sentiment-analysis-with-kafka-and-sagemaker/index.md
Labels: tutorial, ready for technical review

#973 Update to Sustainable Software Development Life Cycle (S-SDLC)
  posts/sustainable-sdlc/index.md
Labels: add to wave/space

#921 [New tutorial] Vector Embeddings and RAG Demystified - Part 1
  concepts/vector-embeddings-and-rag-demystified/images/amazon-shopping.png
  concepts/vector-embeddings-and-rag-demystified/images/distance.png
  concepts/vector-embeddings-and-rag-demystified/images/hnsw_1.png
  concepts/vector-embeddings-and-rag-demystified/images/hnsw_2.png
  concepts/vector-embeddings-and-rag-demystified/images/hnsw_3.png
  concepts/vector-embeddings-and-rag-demystified/images/hnsw_4.png
  concepts/vector-embeddings-and-rag-demystified/images/lsh_1.png
  concepts/vector-embeddings-and-rag-demystified/images/lsh_2.png
  concepts/vector-embeddings-and-rag-demystified/images/po_1.png
  concepts/vector-embeddings-and-rag-demystified/images/po_2.png
  concepts/vector-embeddings-and-rag-demystified/images/po_3.png
  concepts/vector-embeddings-and-rag-demystified/index.md
Labels: tutorial, ready for final review

#936 [New tutorial] Vector Embeddings and RAG Demystified - Part 2
  concepts/vector-embeddings-and-rag-demystified-2/images/rag.png
  concepts/vector-embeddings-and-rag-demystified-2/images/sql_lc_show_tables.png
  concepts/vector-embeddings-and-rag-demystified-2/images/sql_lc_show_tables_2.png
  concepts/vector-embeddings-and-rag-demystified-2/images/sql_lc_show_tables_3.png
  concepts/vector-embeddings-and-rag-demystified-2/images/sql_lc_show_tables_4.png
  concepts/vector-embeddings-and-rag-demystified-2/images/sql_lc_show_tables_5.png
  concepts/vector-embeddings-and-rag-demystified-2/images/vector_store_aws.png
  concepts/vector-embeddings-and-rag-demystified-2/index.md
Labels: tutorial, ready for editorial review, technical review complete

#865 [New Tutorial] Protecting Amazon DynamoDB Using AWS Backup
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image01.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image02.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image03.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image04.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image05.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image06.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image07.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image08.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image09.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image10.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image11.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image12.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image13.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image14.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image15.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image16.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image17.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image18.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image19.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image20.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image21.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image22.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image23.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image24.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image25.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image26.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/images/image27.png
  tutorials/protecting-amazon-dynamoDB-using-aws-backup/index.md
Labels: tutorial, ready for final review

#946 [New post] Getting Started With Your Raspberry Pi Pico W and AWS IoT Core in under 15 minutes
  concepts/getting-started-with-pico-w-iot-core/images/CloudShell_actions_menu.jpg
  concepts/getting-started-with-pico-w-iot-core/images/CloudShell_console_icon.png
  concepts/getting-started-with-pico-w-iot-core/images/CloudShell_download_cert.jpg
  concepts/getting-started-with-pico-w-iot-core/images/CloudShell_download_key.jpg
  concepts/getting-started-with-pico-w-iot-core/images/MQTT_client_subscribe.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_certs_folder.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_certs_on_pico_w.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_device_selection_window.png
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_main_py_file.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_menu_run_button.png
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_new_directory.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_new_file.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_panes.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_toolbar.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_umqtt_simple_install_screen.jpg
  concepts/getting-started-with-pico-w-iot-core/images/Thonny_umqtt_simple_package.jpg
  concepts/getting-started-with-pico-w-iot-core/index.md
Labels: technical review complete, quick guide, 8112, ready for final review
