Repository build-on-aws/content, pull requests merged in 2023-06, with the labels that each got.

#373 Build a Serverless Application to Automate Invoice Processing on AWS
  tutorials/invoice-processing-textract-lambda-golang/images/diagram.jpg
  tutorials/invoice-processing-textract-lambda-golang/images/output.jpg
  tutorials/invoice-processing-textract-lambda-golang/index.md
Labels: ready to be published, Blog, technical review complete, from-private-fork

#389 [FIX] Changing image issues on the Build On Weekly livestream page.
  livestreams/build-on-weekly/index.md
Labels: from-private-fork

#374 Auto-scaling Kinesis Data Streams applications on Kubernetes
  posts/auto-scaling-kinesis-data-streams-apps-on-kubernetes/images/arch.jpg
  posts/auto-scaling-kinesis-data-streams-apps-on-kubernetes/images/control-table1.png
  posts/auto-scaling-kinesis-data-streams-apps-on-kubernetes/images/control-table2.jpg
  posts/auto-scaling-kinesis-data-streams-apps-on-kubernetes/images/table1.jpg
  posts/auto-scaling-kinesis-data-streams-apps-on-kubernetes/images/table2.jpg
  posts/auto-scaling-kinesis-data-streams-apps-on-kubernetes/index.md
Labels: final review, Blog, from-private-fork

#426 DDB safe list updates
  posts/ddb-safe-list-updates/images/ddb-put-result.png
  posts/ddb-safe-list-updates/images/set-cannot-be-empty.png
  posts/ddb-safe-list-updates/images/storing-friends-as-string-set.png
  posts/ddb-safe-list-updates/index.md
Labels: ready for review

#419 New post: Build a Serverless Application for Image Label Detection
  tutorials/label-detection-rekognition-lambda-golang/images/diagram.jpg
  tutorials/label-detection-rekognition-lambda-golang/images/output.jpg
  tutorials/label-detection-rekognition-lambda-golang/index.md
Labels: tutorial, technical review complete

#422 New post: Learn how to build a real-time streaming analytics application on Apache Kafka (based on PR 397)
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/add_files_to_bucket.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/architecture.jpg
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/bucket_delete.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/chrome_warning.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/cloudformation_delete.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/create_bucket.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/create_bucket_2.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/create_stack.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ec2_export.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ec2_instances_connect.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ec2_running.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ec2_sudo.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ec2_topics.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ecs_container_overrides.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ecs_create.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ecs_task_definition.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ecs_task_running.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/ecs_vpc.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/flink_build.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/kda_configure.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/kda_dag.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/kda_open_dashboard.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/kda_run_application.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/kda_running_jobs.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/kda_runtime_properties.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/msk_cluster_endpoint.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/msk_cluster_information.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/msk_cluster_settings.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/msk_delete.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/msk_vpc_settings.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/opensearch_dashboard.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/opensearch_graphs.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/opensearch_login.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/schema_properties.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/schema_version_definition.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/specify_stack_details.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/stack_outputs.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/stack_progress.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/images/upload_to_bucket.png
  posts/building-real-time-streaming-analytics-application-on-apache-kafka/index.md
Labels: final review, tutorial, technical review complete, editorial review complete

#392 New post - Building an AWS Solution Architect Agent with Generative AI
  posts/building-agent-aws/images/code_example.png
  posts/building-agent-aws/images/diagram_example.png
  posts/building-agent-aws/images/query_example.png
  posts/building-agent-aws/index.md
Labels: Blog, technical review complete, editorial review complete

#449 New post: All the things that Comprehend, Rekognition, Textract, Polly, Transcribe and others do
  posts/all-the-things-that-comprehend-rekognition-textract-polly-transcribe-and-others-do/images/create-subtitles-and-translate-s.png
  posts/all-the-things-that-comprehend-rekognition-textract-polly-transcribe-and-others-do/images/detecting-entities-and-sentiment.png
  posts/all-the-things-that-comprehend-rekognition-textract-polly-transcribe-and-others-do/images/diagram-api-call.png
  posts/all-the-things-that-comprehend-rekognition-textract-polly-transcribe-and-others-do/images/make-polly-talk.png
  posts/all-the-things-that-comprehend-rekognition-textract-polly-transcribe-and-others-do/images/video-content-moderation.png
  posts/all-the-things-that-comprehend-rekognition-textract-polly-transcribe-and-others-do/index.md
Labels: Blog, technical review complete, editorial review complete

#414 New post: Practical cloud guide - We're Moving to the Cloud
  tutorials/practical-cloud-guide/series.md
  tutorials/practical-cloud-guide/were-moving-to-the-cloud-a-practical-guide-to-cloud-migration/images/sysadmin_monday_surprise.jpeg
  tutorials/practical-cloud-guide/were-moving-to-the-cloud-a-practical-guide-to-cloud-migration/index.md
Labels: Blog, ready for editorial review, recreated-pr

#423 Building a serverless image recognition website with ML
  posts/cloud-journeys/01-serverless-image-recognition-app/images/dynamodb.png
  posts/cloud-journeys/01-serverless-image-recognition-app/images/hostedui.png
  posts/cloud-journeys/01-serverless-image-recognition-app/images/labels.png
  posts/cloud-journeys/01-serverless-image-recognition-app/images/upload.png
  posts/cloud-journeys/01-serverless-image-recognition-app/index.md
  posts/cloud-journeys/series.md
Labels: ready to be published, Blog, technical review complete, editorial review complete

#471 New Post: Introduction to Artificial Intelligence and Machine Learning
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_1.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_10.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_11.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_12.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_13.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_14.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_15.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_16.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_2.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_3.jpg
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_4.jpg
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_5.jpg
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_6.jpg
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_7.jpg
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_8.jpg
  posts/introduction-to-artificial-intelligence-and-machine-learning/images/fig_9.png
  posts/introduction-to-artificial-intelligence-and-machine-learning/index.md
Labels: Blog

#474 New post: What is an Insecure Direct Object Reference
  posts/owasp-top-10-defined/04-what-is-an-insecure-direct-object-reference/images/developer-tools-modified-request.png
  posts/owasp-top-10-defined/04-what-is-an-insecure-direct-object-reference/images/developer-tools-modify-request.png
  posts/owasp-top-10-defined/04-what-is-an-insecure-direct-object-reference/images/developer-tools-response-01.png
  posts/owasp-top-10-defined/04-what-is-an-insecure-direct-object-reference/images/juice-shop-basket.png
  posts/owasp-top-10-defined/04-what-is-an-insecure-direct-object-reference/images/juice-shop-home.png
  posts/owasp-top-10-defined/04-what-is-an-insecure-direct-object-reference/index.md
  posts/owasp-top-10-defined/series.md
Labels: Blog, technical review complete, editorial review complete

#406 New Content: Event-Driven Architectures: Service Orchestration vs. Choreography
  concepts/event-driven-architectures-service-orchestration-vs-choreography/images/choreography-vs-orchestration.png
  concepts/event-driven-architectures-service-orchestration-vs-choreography/index.md
Labels: ready for editorial review, technical review complete, stale-PR, recreated-pr

#396 New post: Understanding Integration Patterns in Event-Driven Architecture – First draft
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/asynchronous-message-router-model-event-bus.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/asynchronous-point-to-point-queue.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/asynchronous-point-to-point-sender-router.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/dead-letter-queue-dlq.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/sample-event-driven-architecture.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/sample-workflow-saga-pattern.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/sample-workflow.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/images/synchronous-request-response-model.png
  concepts/understanding-integration-patterns-in-event-driven-architecture/index.md
Labels: changes requested, stale-PR, recreated-pr

#436 New post: Build a Serverless Application for Audio to Text conversion
  tutorials/audio-to-text-transcribe-lambda-golang/images/diagram.jpg
  tutorials/audio-to-text-transcribe-lambda-golang/images/job.jpg
  tutorials/audio-to-text-transcribe-lambda-golang/index.md
Labels: tutorial, ready for technical review

#437 Start an EC2 Mac instance
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/images/dedicated-host.png
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/images/ec2-actions.png
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/images/ec2-mac-launch.png
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/images/mac-mini-ec2.png
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/images/macos-amis.png
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/images/saving-plans.png
  tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
  tutorials/ec2-mac/series.md
Labels: accepted, tutorial, ready for technical review, recreated-pr

#438 Connect to an EC2 Mac instance
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/archi-ssh-tunnel.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/ec2-connect-1.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/ec2-connect-2.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/ec2-connect-3.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/ssh-ec2-instance.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/vnc-credentials.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/vnc-mac-desktop.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/images/vnc-mac-login.png
  tutorials/ec2-mac/02-connect-to-an-ec2-mac-instance/index.md
Labels: accepted, tutorial, ready for technical review, recreated-pr

#399 New post: How I got started Learning AI-ML
  posts/how-i-got-started-learning-ai-ml/images/figure1.jpg
  posts/how-i-got-started-learning-ai-ml/images/figure2.jpg
  posts/how-i-got-started-learning-ai-ml/images/figure3.jpg
  posts/how-i-got-started-learning-ai-ml/images/figure4.png
  posts/how-i-got-started-learning-ai-ml/index.md
Labels: Blog, technical review complete, editorial review complete, recreated-pr

#439 New post: Empowering SQL developers with real time data analytics and Apache Flink
  posts/real-time-analytics-with-flink-sql/images/IAM_1.png
  posts/real-time-analytics-with-flink-sql/images/IAM_2.png
  posts/real-time-analytics-with-flink-sql/images/KDS.png
  posts/real-time-analytics-with-flink-sql/images/Q1_output.jpg
  posts/real-time-analytics-with-flink-sql/images/Q2_output.png
  posts/real-time-analytics-with-flink-sql/images/S3.png
  posts/real-time-analytics-with-flink-sql/images/Zeppelin_1.png
  posts/real-time-analytics-with-flink-sql/images/Zeppelin_create_note.png
  posts/real-time-analytics-with-flink-sql/images/architecture.png
  posts/real-time-analytics-with-flink-sql/index.md
Labels: Blog

#443 New post: Deploy an ASP.NET Core Application on Windows Server with AWS Lightsail
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-1-lightsail-storage.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-1-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-2-lightsail-storage.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-2-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-3-lightsail-storage.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-3-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-4-lightsail-storage.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-4-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-5-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-6-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-7-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-9-lightsail.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-lightsail-RDP.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/PCG-lightsail-launch-script.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/delete-vps-1.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/delete-vps-2.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/delete-vps-3.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-1.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-2.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-3.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-4.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-5.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-6.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/lightsail-s3-bucket-7.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/s3-delete-1.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/s3-delete-2.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/images/s3-delete-3.png
  tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
Labels: final review, tutorial
