Repository build-on-aws/content, pull requests merged in 2023-11, with the labels that each got.

#840 [New post - publish after 10/26 only] Generative AI for Go developers - Build a Serverless image generation solution using Amazon Bedrock
  tutorials/amazon-bedrock-lambda-image-gen-golang/images/cfn-info.png
  tutorials/amazon-bedrock-lambda-image-gen-golang/images/cfn.png
  tutorials/amazon-bedrock-lambda-image-gen-golang/images/config.png
  tutorials/amazon-bedrock-lambda-image-gen-golang/images/diagram.png
  tutorials/amazon-bedrock-lambda-image-gen-golang/images/website.jpg
  tutorials/amazon-bedrock-lambda-image-gen-golang/index.md
Labels: editorial review in progress, tutorial, technical review complete, 8112, ready for final review, author revisions complete

#892 Choosing The Right Chaos Engineering Tool for the Job
  posts/choosing-the-right-chaos-engineering-tool-for-the-job/images/three-tier-multi-az.png
  posts/choosing-the-right-chaos-engineering-tool-for-the-job/index.md
Labels: blog, ready for one-step review

#887 [New post] Building Custom LangChain Agents and Tools with Amazon Bedrock
  posts/amazon-bedrock-custom-langchain-agent/images/agent_aws_pic.webp
  posts/amazon-bedrock-custom-langchain-agent/images/agent_thought_2.webp
  posts/amazon-bedrock-custom-langchain-agent/images/agent_thought_3.webp
  posts/amazon-bedrock-custom-langchain-agent/index.md
Labels: blog, ready for one-step review

#899 [POST]We've got the (AWS) Solution
  posts/weve-got-the-aws-solution/index.md
Labels: blog, ready for one-step review

#895 Sustainable Software Development Life Cycle (S-SDLC)
  posts/sustainable-sdlc/images/s-sdlc-phases.jpg
  posts/sustainable-sdlc/index.md
Labels: blog, ready for one-step review

#900 [Post] Lightsail vs AWS Compute: Comparing Costs with AWS Pricing Calculator
  posts/lightsail-vs-aws-compute-comparing-costs-with-aws-pricing-calculator/index.md
Labels: blog, ready for one-step review

#901 [New post] Building LangChain applications with Amazon Bedrock and Go - An introduction
  posts/amazon-bedrock-langchaingo-llm/index.md
Labels: blog, ready for one-step review

#903 [Post] Run Large Language Models with Ollama and AWS Lightsail for Research
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/jupyter-1.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/jupyter-2.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/jupyter-3.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/jupyter-4.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/jupyter-5.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-1.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-2.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-3.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-4.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-5.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-6.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-7.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-8.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/images/lfr-9.png
  posts/run-large-language-models-with-ollama-and-lightsail-for-research/index.md
Labels: blog, ready for one-step review

#893 Adding show notes for s2ep4
  livestreams/build-on-answered/2023-11-01/images/SDK.jpeg
  livestreams/build-on-answered/2023-11-01/index.md
  livestreams/build-on-answered/index.md
Labels: livestream

#861 [New Tutorial] S3 Batch operations
  tutorials/s3-batch-operations-restore/Images/firstimage.png
  tutorials/s3-batch-operations-restore/Images/image(1).png
  tutorials/s3-batch-operations-restore/Images/image(10).png
  tutorials/s3-batch-operations-restore/Images/image(11).png
  tutorials/s3-batch-operations-restore/Images/image(12).png
  tutorials/s3-batch-operations-restore/Images/image(13).png
  tutorials/s3-batch-operations-restore/Images/image(14).png
  tutorials/s3-batch-operations-restore/Images/image(15).png
  tutorials/s3-batch-operations-restore/Images/image(16).png
  tutorials/s3-batch-operations-restore/Images/image(17).png
  tutorials/s3-batch-operations-restore/Images/image(18).png
  tutorials/s3-batch-operations-restore/Images/image(19).png
  tutorials/s3-batch-operations-restore/Images/image(2).png
  tutorials/s3-batch-operations-restore/Images/image(20).png
  tutorials/s3-batch-operations-restore/Images/image(21).png
  tutorials/s3-batch-operations-restore/Images/image(22).png
  tutorials/s3-batch-operations-restore/Images/image(23).png
  tutorials/s3-batch-operations-restore/Images/image(24).png
  tutorials/s3-batch-operations-restore/Images/image(25).png
  tutorials/s3-batch-operations-restore/Images/image(26).png
  tutorials/s3-batch-operations-restore/Images/image(27).png
  tutorials/s3-batch-operations-restore/Images/image(28).png
  tutorials/s3-batch-operations-restore/Images/image(29).png
  tutorials/s3-batch-operations-restore/Images/image(3).png
  tutorials/s3-batch-operations-restore/Images/image(4).png
  tutorials/s3-batch-operations-restore/Images/image(5).png
  tutorials/s3-batch-operations-restore/Images/image(6).png
  tutorials/s3-batch-operations-restore/Images/image(7).png
  tutorials/s3-batch-operations-restore/Images/image(8).png
  tutorials/s3-batch-operations-restore/Images/image(9).png
  tutorials/s3-batch-operations-restore/Images/secondimage.png
  tutorials/s3-batch-operations-restore/index.md
Labels: tutorial, technical review complete, editorial review complete, 8112, ready for final review

#913 [New blog post] Use LangChain to build "chatterdox", an app to chat with web pages
  posts/amazon-bedrock-apprunner-chatterdox-webapp/images/apprunner-chatterdox.png
  posts/amazon-bedrock-apprunner-chatterdox-webapp/images/arch.jpg
  posts/amazon-bedrock-apprunner-chatterdox-webapp/images/chatgpt.png
  posts/amazon-bedrock-apprunner-chatterdox-webapp/images/chatterdox1.png
  posts/amazon-bedrock-apprunner-chatterdox-webapp/images/chatterdox2.png
  posts/amazon-bedrock-apprunner-chatterdox-webapp/images/chatterdox3.jpg
  posts/amazon-bedrock-apprunner-chatterdox-webapp/index.md
Labels: blog, ready for one-step review

#871 New post: Getting Started with Ray on AWS
  posts/launching-ray-clusters-on-aws/index.md
Labels: blog, ready for one-step review

#909 [NEW POST] "Hey, computer: talk to me in Polish! Building a Polish-language speaking chatbot with Amazon SageMaker, Hugging Face, TRURL 2, and Streamlit"
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/exploration-1-open-notebook.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/exploration-2-configure-kernel.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/setup-1-clone-repository.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/setup-2-clone-aws-codecommit-repository.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/setup-3-open-launcher.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/setup-4-open-system-terminal.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/streamlit-1-final-conversation.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/images/streamlit-2-run-on-sagemaker-studio.png
  concepts/deploying-trurl-2-on-amazon-sagemaker/index.md
Labels: quick guide, add to wave/space, ready for final review

#879 Break a monolith with Refactor Spaces and AWS Copilot tutorial
  tutorials/refactor-spaces-copilot-cli/images/breakintomicroservices.jpg
  tutorials/refactor-spaces-copilot-cli/images/docker.jpg
  tutorials/refactor-spaces-copilot-cli/images/monolithoverview.jpg
  tutorials/refactor-spaces-copilot-cli/images/monolithoverviewwithrs.jpg
  tutorials/refactor-spaces-copilot-cli/images/monotomicro.jpg
  tutorials/refactor-spaces-copilot-cli/images/outputafterrefactoring.jpg
  tutorials/refactor-spaces-copilot-cli/images/outputafterrefactoring.png
  tutorials/refactor-spaces-copilot-cli/images/outputafterrs.jpg
  tutorials/refactor-spaces-copilot-cli/images/outputafterrs.png
  tutorials/refactor-spaces-copilot-cli/images/processflow.jpg
  tutorials/refactor-spaces-copilot-cli/images/processofdecomposing.jpg
  tutorials/refactor-spaces-copilot-cli/images/rsconsole.webp
  tutorials/refactor-spaces-copilot-cli/images/whatyouwilldo.jpg
  tutorials/refactor-spaces-copilot-cli/index.md
Labels: tutorial, 8112, ready for final review

#906 [New post] How to build accurate and cost-efficient identity verification and intelligent document processing solution for financial use case
  concepts/create-idv-idp-machine-learning-solution/images/FaceLivenessDetector_UIAmplify.png
  concepts/create-idv-idp-machine-learning-solution/images/Mortgage-Identity_Verification.png
  concepts/create-idv-idp-machine-learning-solution/images/Mortgage-Intelligent_Document_Processing.png
  concepts/create-idv-idp-machine-learning-solution/images/Mortgage-Liveness_detection.png
  concepts/create-idv-idp-machine-learning-solution/images/Mortgage-Process flow.png
  concepts/create-idv-idp-machine-learning-solution/images/Mortgage-Reference_Architecture.png
  concepts/create-idv-idp-machine-learning-solution/index.md
Labels: deep dive, 8112, ready for final review

#919 [re:Invent] Cloud Operations guide to sessions at reinvent
  posts/cloudops-at-reinvent23/images/cfm.webp
  posts/cloudops-at-reinvent23/images/govern.webp
  posts/cloudops-at-reinvent23/images/observability.webp
  posts/cloudops-at-reinvent23/index.md
Labels: blog, ready for one-step review, add to wave/space

#922 [New post] 5 Things to Consider When Building Your First Generative AI Application On AWS
  posts/5-things-to-consider-first-genai-application-on-aws/index.md
Labels: blog, ready for one-step review

#923 [New post] Deploy WordPress with Lightsail and CloudFormation
  posts/deploy-wordpress-with-lightsail-and-cloudFormation/index.md
Labels: blog, ready for one-step review

#926 Modify wording to reflect the scope of the series
  posts/owasp-application-vulnerabilities/01-what-is-broken-access-control/index.md
  posts/owasp-application-vulnerabilities/02-what-is-a-cryptographic-failure/index.md
  posts/owasp-application-vulnerabilities/03-what-is-an-injection-attack/images/03-what-is-an-injection-attack-01.png
  posts/owasp-application-vulnerabilities/03-what-is-an-injection-attack/images/03-what-is-an-injection-attack-02.png
  posts/owasp-application-vulnerabilities/03-what-is-an-injection-attack/images/03-what-is-an-injection-attack-03.gif
  posts/owasp-application-vulnerabilities/03-what-is-an-injection-attack/images/03-what-is-an-injection-attack-04.png
  posts/owasp-application-vulnerabilities/03-what-is-an-injection-attack/images/03-what-is-an-injection-attack-05.png
  posts/owasp-application-vulnerabilities/03-what-is-an-injection-attack/index.md
  posts/owasp-application-vulnerabilities/04-what-is-an-insecure-direct-object-reference/images/developer-tools-modified-request.png
  posts/owasp-application-vulnerabilities/04-what-is-an-insecure-direct-object-reference/images/developer-tools-modify-request.png
  posts/owasp-application-vulnerabilities/04-what-is-an-insecure-direct-object-reference/images/developer-tools-response-01.png
  posts/owasp-application-vulnerabilities/04-what-is-an-insecure-direct-object-reference/images/juice-shop-basket.png
  posts/owasp-application-vulnerabilities/04-what-is-an-insecure-direct-object-reference/images/juice-shop-home.png
  posts/owasp-application-vulnerabilities/04-what-is-an-insecure-direct-object-reference/index.md
  posts/owasp-application-vulnerabilities/series.md
  posts/owasp-top-10-defined/series.md
Labels: ready for one-step review

#934 [Post] Automate WordPress Lightsail Deployments with AWS CDK
  posts/automate-wordpress-lightsail-deployments-with-aws-cdk/images/cdk-1.png
  posts/automate-wordpress-lightsail-deployments-with-aws-cdk/images/cdk-2.png
  posts/automate-wordpress-lightsail-deployments-with-aws-cdk/images/cdk-3.png
  posts/automate-wordpress-lightsail-deployments-with-aws-cdk/images/cdk-4.png
  posts/automate-wordpress-lightsail-deployments-with-aws-cdk/images/cdk-5.png
  posts/automate-wordpress-lightsail-deployments-with-aws-cdk/index.md
Labels: blog, ready for one-step review

#940 [New post] Amazon Search Chaos Engineering Journey
  posts/amazon-search-chaos-engineering-journey/images/figure1.jpg
  posts/amazon-search-chaos-engineering-journey/images/figure3.png
  posts/amazon-search-chaos-engineering-journey/images/figure4.png
  posts/amazon-search-chaos-engineering-journey/index.md
Labels: blog, ready for one-step review

#938 [New post] Amazon Search Chaos Engineering Journey
  posts/amazon-search-chaos-engineering-journey/images/figure1.png
  posts/amazon-search-chaos-engineering-journey/images/figure3.png
  posts/amazon-search-chaos-engineering-journey/images/figure4.png
  posts/amazon-search-chaos-engineering-journey/index.md
Labels: blog, ready for one-step review

#947 luca-and-matt-lambda-post
  posts/improved-lambda-warm-start-speed-95/images/headerimage.webp
  posts/improved-lambda-warm-start-speed-95/images/image_1.png
  posts/improved-lambda-warm-start-speed-95/images/image_10.png
  posts/improved-lambda-warm-start-speed-95/images/image_11.png
  posts/improved-lambda-warm-start-speed-95/images/image_12.png
  posts/improved-lambda-warm-start-speed-95/images/image_13.png
  posts/improved-lambda-warm-start-speed-95/images/image_14.png
  posts/improved-lambda-warm-start-speed-95/images/image_15.webp
  posts/improved-lambda-warm-start-speed-95/images/image_16.webp
  posts/improved-lambda-warm-start-speed-95/images/image_17.png
  posts/improved-lambda-warm-start-speed-95/images/image_18.png
  posts/improved-lambda-warm-start-speed-95/images/image_2.png
  posts/improved-lambda-warm-start-speed-95/images/image_3.png
  posts/improved-lambda-warm-start-speed-95/images/image_4.png
  posts/improved-lambda-warm-start-speed-95/images/image_5.png
  posts/improved-lambda-warm-start-speed-95/images/image_6.webp
  posts/improved-lambda-warm-start-speed-95/images/image_7.png
  posts/improved-lambda-warm-start-speed-95/images/image_8.webp
  posts/improved-lambda-warm-start-speed-95/images/image_9.png
  posts/improved-lambda-warm-start-speed-95/index.md
Labels: ready for one-step review

#950 [New post] Add Files via upload for "Use Generative AI..."
  posts/use-generative-ai-to-name-your-pet-after-your-favorite-song/images/Use-Generative-AI-to-Name-Your-Pet-After-Your-Favorite-Song0.webp
  posts/use-generative-ai-to-name-your-pet-after-your-favorite-song/images/Use-Generative-AI-to-Name-Your-Pet-After-Your-Favorite-Song1.webp
  posts/use-generative-ai-to-name-your-pet-after-your-favorite-song/images/Use-Generative-AI-to-Name-Your-Pet-After-Your-Favorite-Song2.webp
  posts/use-generative-ai-to-name-your-pet-after-your-favorite-song/images/Use-Generative-AI-to-Name-Your-Pet-After-Your-Favorite-Song3.webp
  posts/use-generative-ai-to-name-your-pet-after-your-favorite-song/index.md
Labels: blog, ready for one-step review

#910 [NEW POST] "Beware the Stateless vs. Stateful Fallacies: Making Informed Decisions in System Design"
  posts/beware-the-stateless-vs-stateful-fallacies-making-informed-decisions-in-system-design/index.md
Labels: on hold, blog, ready for one-step review, add to wave/space

#905 [New Tutorial] Deploying Amazon EKS Windows managed node groups and Fargate nodes
  tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/images/fargate-windows.png
  tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/images/web-app.png
  tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
Labels: tutorial, 8112, ready for final review, editorial re-review complete
