Repository build-on-aws/content, pull requests merged in 2023-09, with the labels that each got.

#708 Scaling Distributed Systems with Event Sourcing, CQRS, and AWS Serverless
  posts/scaling-distributed-systems-event-sourcing-cqrs-serverless/images/crud_data_access_model.png
  posts/scaling-distributed-systems-event-sourcing-cqrs-serverless/images/event_sourcing_and_cqrs_pattern.png
  posts/scaling-distributed-systems-event-sourcing-cqrs-serverless/images/event_sourcing_pattern.png
  posts/scaling-distributed-systems-event-sourcing-cqrs-serverless/images/serverless_cqrs_scaleout.png
  posts/scaling-distributed-systems-event-sourcing-cqrs-serverless/images/serverless_cqrs_simple.png
  posts/scaling-distributed-systems-event-sourcing-cqrs-serverless/index.md
Labels: published, blog, ready for one-step review

#702 how-search-uses-chaos-engineering initial commit
  posts/how-search-uses-chaos-engineering/images/figure1.webp
  posts/how-search-uses-chaos-engineering/images/figure2.png
  posts/how-search-uses-chaos-engineering/images/figure3.png
  posts/how-search-uses-chaos-engineering/images/figure4.png
  posts/how-search-uses-chaos-engineering/images/figure5.webp
  posts/how-search-uses-chaos-engineering/index.md
Labels: blog, ready for one-step review

#711 Post/start projects with cicd
  posts/start-your-projects-with-a-cicd-pipeline/images/cicd-pipeline.png
  posts/start-your-projects-with-a-cicd-pipeline/images/project-investment.png
  posts/start-your-projects-with-a-cicd-pipeline/images/reasons-why.png
  posts/start-your-projects-with-a-cicd-pipeline/index.md
Labels: published, blog, community contribution, ready for one-step review

#713 minor updates to blogpost
  posts/real-stories-of-cost-optimization-on-aws/images/cost-optimization.jpeg
  posts/real-stories-of-cost-optimization-on-aws/index.md
Labels: ready for one-step review

#714 [New Post] Cost Conscious Disaster Recovery
  posts/cost-conscious-disaster-recovery/images/Architecture.png
  posts/cost-conscious-disaster-recovery/images/Grafana-Dashboard.jpg
  posts/cost-conscious-disaster-recovery/index.md
Labels: published, blog, ready for one-step review

#716 added cost space to published blog
  posts/cost-conscious-disaster-recovery/index.md
Labels: add to wave/space

#703 Post: How to build and manage a resilient service
  posts/build-and-manage-a-resilient-service-using-aws-sdks/index.md
Labels: published, blog, ready for one-step review

#717 Vector Databases: Powering the GenAI Revolution
  posts/vector-databases-powering-the-genai-revolution/images/vector-db-header.gif
  posts/vector-databases-powering-the-genai-revolution/index.md
Labels: published, blog, ready for one-step review

#513 [New Fundamentals] Balancing Performance and Cost: How to Choose the Right AWS Storage Solution for Your Applications
  posts/optimizing-cost-with-different-data-storage-options/images/StorageServices.jpg
  posts/optimizing-cost-with-different-data-storage-options/index.md
Labels: fundamentals, technical review complete, editorial review complete, 8112

#691 Run Kubernetes Clusters for Less with Amazon EC2 Spot and Karpenter
  tutorials/run-kubernetes-clusters-for-less-with-amazon-ec2-spot-and-karpenter/index.md
Labels: final review, tutorial, technical review complete, editorial review complete, 8112

#608 [New Fundamental] Resilient cloud architecture - 200 level overview
  concepts/should-know-resilience/images/equation1.png
  concepts/should-know-resilience/images/equation2.png
  concepts/should-know-resilience/images/figure1.png
  concepts/should-know-resilience/images/figure2.png
  concepts/should-know-resilience/images/figure3.png
  concepts/should-know-resilience/images/figure4.png
  concepts/should-know-resilience/index.md
Labels: final review, foundational

#721 [New Post] 5 ways to cost optimize your Infrastructure as Code
  posts/5-ways-to-cost-optimize-your-Infrastructure-as-Code/index.md
Labels: blog, ready for one-step review

#722 [New Post] Building Sustainable Cloud Solutions with 3 Green Design Principles
  posts/building-sustainable-cloud-solutions-with-3-green-design-principles/index.md
Labels: published, blog, ready for one-step review

#725 [New Post] Scale across borders: build a multi-region architecture while maintaining data residency
  posts/scale-beyond-borders/images/cover.jpg
  posts/scale-beyond-borders/images/multi-region-architecture.png
  posts/scale-beyond-borders/index.md
Labels: published, blog, ready for one-step review

#641 [New Tutorial] How to Setup Replication Lag Monitoring for Amazon DynamoDB GlobalTables
  tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
  tutorials/ddb-globaltables-lag/ss1.png
  tutorials/ddb-globaltables-lag/ss2.png
  tutorials/ddb-globaltables-lag/ss3.png
  tutorials/ddb-globaltables-lag/ss4.png
  tutorials/ddb-globaltables-lag/ss5.png
  tutorials/ddb-globaltables-lag/ss6.png
Labels: tutorial, ready for editorial review, technical review complete, 8112

#657 [New Post] Rightsizing-the right way
  posts/rightsizing-the-right-way/images/AWS-CE-RightSizing.jpg
  posts/rightsizing-the-right-way/images/AWS-CE-RightSizing2.jpg
  posts/rightsizing-the-right-way/images/AWS-Compute-Optimizer.jpg
  posts/rightsizing-the-right-way/images/AWS-trusted-advisor.jpg
  posts/rightsizing-the-right-way/images/Amazon-CloudWatch.jpg
  posts/rightsizing-the-right-way/images/Compute-Optimizer-1.jpg
  posts/rightsizing-the-right-way/images/Compute-Optimizer-2.jpg
  posts/rightsizing-the-right-way/images/Compute-Optimizer-3.jpg
  posts/rightsizing-the-right-way/images/Compute-Optimizer-4.jpg
  posts/rightsizing-the-right-way/images/Compute-Optimizer-Find.jpg
  posts/rightsizing-the-right-way/images/aws-instance-type-name.jpg
  posts/rightsizing-the-right-way/index.md
Labels: published, blog, ready for one-step review

#746 adding cost spaces to 2 blogs
  posts/building-sustainable-cloud-solutions-with-3-green-design-principles/index.md
  posts/rightsizing-the-right-way/index.md
Labels: add to wave/space

#743 [New Post] - Generative AI for Edu
  posts/genai-for-edu/images/banner.jpg
  posts/genai-for-edu/images/chat-tutor.jpg
  posts/genai-for-edu/index.md
Labels: published, blog, ready for one-step review

#750 Build A Translator App in 30 Min or Less
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_1.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_10.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_11.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_12.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_13.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_14.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_2.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_3.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_4.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_5.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_6.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_7.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_8.png
  tutorials/build-your-own-translator-app-in-less-30-min/images/fig_9.png
  tutorials/build-your-own-translator-app-in-less-30-min/index.md
Labels: tutorial, technical review complete, editorial review complete

#646 New post: Using Java, Amazon Corretto, Ukulele and Fast Fourier Transform to detect musical notes and command IoT devices
  posts/fourier-iot/images/architecture1.png
  posts/fourier-iot/images/fourier1.jpg
  posts/fourier-iot/images/fourier2.jpg
  posts/fourier-iot/images/iot01.png
  posts/fourier-iot/images/iot02.png
  posts/fourier-iot/images/iot03.png
  posts/fourier-iot/images/iot04.png
  posts/fourier-iot/images/iot05.png
  posts/fourier-iot/images/iot06.png
  posts/fourier-iot/images/iot07.png
  posts/fourier-iot/images/iot08.png
  posts/fourier-iot/images/iot09.png
  posts/fourier-iot/images/iot10.png
  posts/fourier-iot/images/processing1.jpg
  posts/fourier-iot/images/processing2.png
  posts/fourier-iot/images/processing3.png
  posts/fourier-iot/images/processing4.png
  posts/fourier-iot/images/processing5.png
  posts/fourier-iot/index.md
Labels: changes requested, technical review complete, editorial review complete, quick guide

#690 New Tutorial: Tidy your Bedroom - Identify Unused Resources
  tutorials/tidy-your-bedroom-identify-unused-resources/images/AdobeStock_65680523.jpeg
  tutorials/tidy-your-bedroom-identify-unused-resources/images/AdobeStock_65680526.jpeg
  tutorials/tidy-your-bedroom-identify-unused-resources/images/AdobeStock_65681069.jpeg
  tutorials/tidy-your-bedroom-identify-unused-resources/images/console-search-bar.png
  tutorials/tidy-your-bedroom-identify-unused-resources/images/cost-and-usage.png
  tutorials/tidy-your-bedroom-identify-unused-resources/images/create-view.png
  tutorials/tidy-your-bedroom-identify-unused-resources/images/dynamodb-filter.png
  tutorials/tidy-your-bedroom-identify-unused-resources/images/filtered-view.png
  tutorials/tidy-your-bedroom-identify-unused-resources/images/quick-set-up.png
  tutorials/tidy-your-bedroom-identify-unused-resources/images/turn-on-resource-explorer.png
  tutorials/tidy-your-bedroom-identify-unused-resources/index.md
Labels: final review, tutorial, technical review complete, 8112

#770 Automating Chaos Engineering in Your Delivery Pipelines
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-architecture.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-cloudwatch-in-alarm.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-experiment-completed.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-experiment-stage-failed.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-experiment-stage-in-progress.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-experiment-stage-succeeded.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-experiment-stopped.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-experiment-template.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-new-experiment-stage.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-original-pipeline.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-state-machine-succeeded.jpg
  posts/chaos-engineering-pipeline/images/chaos-engineering-pipeline-state-machine.jpg
  posts/chaos-engineering-pipeline/index.md
Labels: blog, ready for one-step review

#636 [New Tutorial] building-multi-region-disaster-recovery-for-amazon-appstream2.0
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image1.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image10.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image11.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image12.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image2.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image3.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image4.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image5.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image6.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image7.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image8.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image9.png
  tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
Labels: final review, tutorial, 8112

#603 [New Tutorial] Solving Problems You Can't See: Using AWS X-Ray and CloudWatch for user-level observability in your serverless microservices applications
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/api-gateway-authorizers-cognito.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/api-gateway-cognito-authorizer-test.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/api-gateway-serverless-shopping-cart-checkout-post-method.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/api-gateway-serverless-shopping-cart-get-method.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-api-gateway-api-menu.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-api-gateway-serverless-shopping-cart-api.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-lambda-exception-log-correlation.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-lambda-list-cart-function-code-tab.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-lambda-serverless-shopping-cart-list-cart-function.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-serverless-shopping-cart-ui.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-alarm-notification-email.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-create-alarm-2.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-create-alarm-3.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-create-alarm.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-graphed.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-metrics.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-service-map-filter-by-slow-registered-users.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-traces-group-by-registered-users.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/chrome-developer-tools-network-view-header-auth-cookie.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/cloudwatch-x-ray-menu.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/google-chrome-dev-tools-network-view.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/serverless-shopping-cart-homepage.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/serverless-shopping-cart-list-cart-view.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/serverless-shopping-cart-login-screen.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-build-query-add-to-query.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-build-query-refine-by-username-annotation.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-cloudwatch-groups-setting.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-create-group-with-query.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-filter-service-map-by-group.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-filtered-service-map-by-annotation.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-filtered-service-map-empty.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-filtered-service-map.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-run-query.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-segments-annotations-view.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-segments-timeline-exceptions.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-segments-timeline-with-annotations.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-selected-node-with-error.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-serverless-shopping-cart-service-map-displaying-error.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-service-map-diagnose-issue.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-service-map-healthy-view.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-service-map-node-view.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-service-map.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-traces-list.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-traces-map.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-traces-view.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-view-filtered-traces-select-segment-with-error.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-view-filtered-traces.png
  tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
Labels: final review, tutorial, 8112

#775 [New Post] How to build scalable multi domain IP allow-listing using AWS ALB and AWS WAF
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-Add-The-Allow-List-RuleGroup-ToTheAcl.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-AddRule-1.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-AddRule-2.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-AddRule-3.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-AddRule-4.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-Adjust-RuleGroup-Capacity.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-Associate-WebAcl-With-ALB.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-Describe-Rule-Group.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-Describe-WebAcl-and-AssociateItWith-ALB.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/images/Screenshot-create-IPSet.png
  posts/building-scalable-multi-domain-IP-allow-listing-aws-alb-aws-waf/index.md
Labels: blog, ready for one-step review

#778 [New Posts & Series] Sustainable data management practices series
  posts/sustainable-data-management-practices/01-understanding-sustainable-data-management/images/sustainability-shared-responsibility-model.png
  posts/sustainable-data-management-practices/01-understanding-sustainable-data-management/index.md
  posts/sustainable-data-management-practices/02-sustainability-at-the-core-of-data-strategy/images/five-key-principles-for-building-sustainable-data-management.webp
  posts/sustainable-data-management-practices/02-sustainability-at-the-core-of-data-strategy/index.md
  posts/sustainable-data-management-practices/03-transitioning-to-sustainable-data-management/images/lab-solution-architecture.png
  posts/sustainable-data-management-practices/03-transitioning-to-sustainable-data-management/images/table.png
  posts/sustainable-data-management-practices/03-transitioning-to-sustainable-data-management/index.md
  posts/sustainable-data-management-practices/series.md
Labels: blog, ready for one-step review

#781 [New community post] re:Invent uncovered - Top tips for first-time attendees
  posts/reinvent-uncovered/images/teaser.png
  posts/reinvent-uncovered/index.md
Labels: blog, community contribution, ready for one-step review

#780 [New Post] Blog/537 amplify flutter appsync
  posts/amplify-flutter-serverless-with-appsync/images/cicd_workflow.png
  posts/amplify-flutter-serverless-with-appsync/images/high_level_architecture.png
  posts/amplify-flutter-serverless-with-appsync/images/merged_apis_architecture.webp
  posts/amplify-flutter-serverless-with-appsync/images/ui_architecture.webp
  posts/amplify-flutter-serverless-with-appsync/index.md
Labels: blog, community contribution, ready for one-step review

#755 [New Post] Shift Cloud Costs Left
  posts/shifting-cloud-costs-left-what-it-really-means/images/infracost-cost-optimization-formula.png
  posts/shifting-cloud-costs-left-what-it-really-means/index.md
Labels: changes requested, blog, community contribution, ready for one-step review

#782 [New Post] Cloud account fundamentals
  posts/cloud-account-cost-fundamentals/images/Shared_Responsibility_Model_V2.jpg
  posts/cloud-account-cost-fundamentals/images/aws-account-signup.png
  posts/cloud-account-cost-fundamentals/images/aws-console-iam-user-age.png
  posts/cloud-account-cost-fundamentals/images/aws-free-tier-billing-console.png
  posts/cloud-account-cost-fundamentals/images/aws-resource-explorer.png
  posts/cloud-account-cost-fundamentals/images/billing-alert-preferences-update.png
  posts/cloud-account-cost-fundamentals/images/cloudping-info-latency.png
  posts/cloud-account-cost-fundamentals/images/create-budget-aws-console.png
  posts/cloud-account-cost-fundamentals/images/pricing-calculator.png
  posts/cloud-account-cost-fundamentals/images/regions-and-availability-zones.webp
  posts/cloud-account-cost-fundamentals/index.md
Labels: blog, fundamentals, ready for one-step review

#777 [New Post] Looking Beyond Technology In FinOps
  posts/looking-beyond-technology-in-finops/index.md
Labels: blog, community contribution, ready for one-step review

#789 adding cost space and wave to blogs
  posts/cloud-account-cost-fundamentals/index.md
  posts/looking-beyond-technology-in-finops/index.md
  posts/shifting-cloud-costs-left-what-it-really-means/index.md
  posts/sustainable-data-management-practices/01-understanding-sustainable-data-management/index.md
  posts/sustainable-data-management-practices/02-sustainability-at-the-core-of-data-strategy/index.md
  posts/sustainable-data-management-practices/03-transitioning-to-sustainable-data-management/index.md
Labels: add to wave/space

#748 [New Tutorial] Designing Scalable and Versatile Storage Solutions on Amazon EKS with the Amazon EFS CSI
  tutorials/eks-with-efs-add-on/index.md
Labels: editorial review in progress, tutorial, technical review complete, 8112

#732 New tutorial: Managing High-Volume Batch Processing Using Amazon SQS and EKS
  tutorials/managing-high-volume-batch-sqs-eks/index.md
Labels: final review, tutorial, technical review complete, editorial review complete, 8112

#768 New Post: Taylor Swift, deploying on Friday, and the ABCs [publish 29 Sep only]
  posts/taylor-swift-deploying-on-friday-and-the-abcs/images/aws-cloud-captains-nigeria.jpg
  posts/taylor-swift-deploying-on-friday-and-the-abcs/images/aws-on-tour.webp
  posts/taylor-swift-deploying-on-friday-and-the-abcs/images/taylor-swift-with-mic.webp
  posts/taylor-swift-deploying-on-friday-and-the-abcs/index.md
Labels: blog, ready for one-step review

#806 How Good Are AI Coding Companions? "It Depends!
  posts/how-good-are-ai-companions-it-depends/images/AWS_APIs.gif
  posts/how-good-are-ai-companions-it-depends/images/CrossFileExample.gif
  posts/how-good-are-ai-companions-it-depends/images/Documentation.gif
  posts/how-good-are-ai-companions-it-depends/images/Example.gif
  posts/how-good-are-ai-companions-it-depends/images/auto_suggestions.gif
  posts/how-good-are-ai-companions-it-depends/images/code_private.gif
  posts/how-good-are-ai-companions-it-depends/images/code_secure.gif
  posts/how-good-are-ai-companions-it-depends/images/fibonacci.gif
  posts/how-good-are-ai-companions-it-depends/images/regex.gif
  posts/how-good-are-ai-companions-it-depends/index.md
Labels: ready for review, blog, ready for one-step review

#805 Stress testing in the cloud
  posts/stress-testing-in-the-cloud/images/JMeter-GUI.png
  posts/stress-testing-in-the-cloud/images/bridge.jpeg
  posts/stress-testing-in-the-cloud/images/communication.jpeg
  posts/stress-testing-in-the-cloud/images/definescenario.png
  posts/stress-testing-in-the-cloud/images/iteratetest.png
  posts/stress-testing-in-the-cloud/images/load.jpeg
  posts/stress-testing-in-the-cloud/images/loaddistribution.png
  posts/stress-testing-in-the-cloud/images/monitortest.png
  posts/stress-testing-in-the-cloud/images/plantest.png
  posts/stress-testing-in-the-cloud/images/runtest.png
  posts/stress-testing-in-the-cloud/images/slow.jpeg
  posts/stress-testing-in-the-cloud/images/stress.jpeg
  posts/stress-testing-in-the-cloud/images/subscribemarketplace.png
  posts/stress-testing-in-the-cloud/images/testresults.png
  posts/stress-testing-in-the-cloud/index.md
Labels: ready for review, blog, ready for one-step review
