Repository build-on-aws/content, pull requests merged in 2024-01, with the labels that each got.

#1001 BoW Livestream updates for 2024
  livestreams/build-on-weekly/images/wpfordarko-rohini.webp
  livestreams/build-on-weekly/index.md
Labels: livestream

#980 [Updating post] Choosing the Right Chaos Engineering Tool for the Job
  posts/choosing-the-right-chaos-engineering-tool-for-the-job/images/figure1.png
  posts/choosing-the-right-chaos-engineering-tool-for-the-job/images/figure2.png
  posts/choosing-the-right-chaos-engineering-tool-for-the-job/images/figure2a.png
  posts/choosing-the-right-chaos-engineering-tool-for-the-job/index.md
Labels: blog

#918 [New post] How to build a VTubing app with Amazon Interactive Video Service and VRoid
  tutorials/build-a-vtubing-app-with-amazon-ivs-and-vroid/images/simple-vtuber-demo-amazon-ivs.gif
  tutorials/build-a-vtubing-app-with-amazon-ivs-and-vroid/index.md
Labels: published

#930 [New post] What is SageMaker?
  concepts/what-is-sagemaker/images/canvas.png
  concepts/what-is-sagemaker/images/clarify.png
  concepts/what-is-sagemaker/images/datawrangler.png
  concepts/what-is-sagemaker/images/groundtruth.png
  concepts/what-is-sagemaker/images/studio.png
  concepts/what-is-sagemaker/index.md
Labels: published

#939 [New post] Sustainability for Beginners
  concepts/sustainability-for-beginners/images/asdi.jpg
  concepts/sustainability-for-beginners/images/ccft-overview.JPG
  concepts/sustainability-for-beginners/images/climate-change-reasons.JPG
  concepts/sustainability-for-beginners/images/ghg-emission scopes.jpg
  concepts/sustainability-for-beginners/images/rcp.jpg
  concepts/sustainability-for-beginners/images/shared-responsibility.jpg
  concepts/sustainability-for-beginners/index.md
Labels: published

#961 [New post] How to build GenAI application using Amazon Bedrock with AWS PrivateLink to protect your data privacy
  concepts/build-GenAI-app-Bedrock-privateLink/images/PrivateLinkHowItWorks.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/bedrock-endpoint-1.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/bedrock-endpoint-2.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/bedrock-endpoint-3.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/bedrock-endpoint-policy.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/bedrock_az.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/lambda-bedrock-architecture.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/lambda-role-1.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/lambda-role-2.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/lambda-vpc.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/lambda.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/sg_1.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/sg_2.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/test_1.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/test_2.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/test_3.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/vpc_1.png
  concepts/build-GenAI-app-Bedrock-privateLink/images/vpc_2.png
  concepts/build-GenAI-app-Bedrock-privateLink/index.md
Labels: published

#948 [New tutorial] Using GenAI to Generate Custom Amazon IVS Live Stream Backgrounds
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/images/amazon-bedrock-api-gateway-config.png
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/images/amazon-bedrock-api-gateway-confirmation.png
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/images/amazon-bedrock-example-screenshot-background.png
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/images/amazon-bedrock-model-access.png
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/images/amazon-ivs-background-replacement-diagram.png
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/images/amazon-ivs-real-time-background-replacement-demo.gif
  tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
Labels: author revisions requested, technical review in progress, tutorial, author revisions complete

#989 Post: Boosting fintech efficiency with Amazon Bedrock
  posts/boosting-fintech-efficiency-with-amazon-bedrock/images/banner.jpg
  posts/boosting-fintech-efficiency-with-amazon-bedrock/index.md
Labels: tutorial

#998 New show Becoming AWSome
  livestreams/becoming-awsome/2023-12-19/images/sara-WebP.webp
  livestreams/becoming-awsome/2023-12-19/index.md
  livestreams/becoming-awsome/2024-01-09/images/laura-WebP.webp
  livestreams/becoming-awsome/2024-01-09/index.md
  livestreams/becoming-awsome/2024-01-16/images/alioune-webp.webp
  livestreams/becoming-awsome/2024-01-16/index.md
  livestreams/becoming-awsome/images/BA Logo WebP 250x250.webp
  livestreams/becoming-awsome/images/Jenna (2).webp
  livestreams/becoming-awsome/images/Leah3.webp
  livestreams/becoming-awsome/index.md
Labels: livestream

#999 New shows added - lets talk about data show
  livestreams/lets-talk-about-data/2023-10-25/images/show27.jpg
  livestreams/lets-talk-about-data/2023-10-25/index.md
  livestreams/lets-talk-about-data/2023-11-01/images/show28.jpg
  livestreams/lets-talk-about-data/2023-11-01/index.md
  livestreams/lets-talk-about-data/2023-11-15/images/show29.jpg
  livestreams/lets-talk-about-data/2023-11-15/index.md
  livestreams/lets-talk-about-data/2023-11-22/images/show30.jpg
  livestreams/lets-talk-about-data/2023-11-22/index.md
  livestreams/lets-talk-about-data/2023-12-06/images/show31.jpg
  livestreams/lets-talk-about-data/2023-12-06/index.md
  livestreams/lets-talk-about-data/2023-12-20/images/show32.jpg
  livestreams/lets-talk-about-data/2023-12-20/index.md
  livestreams/lets-talk-about-data/2024-01-03/images/show01.jpg
  livestreams/lets-talk-about-data/2024-01-03/index.md
  livestreams/lets-talk-about-data/2024-01-10/images/show02.jpg
  livestreams/lets-talk-about-data/2024-01-10/index.md
  livestreams/lets-talk-about-data/index.md
Labels: livestream
